import React, { useMemo, useState } from "react";
import type { NamingGeographyEntityType, NamingGeographyPattern, NamingGeographyReadModelV1, NamingGeographyRow } from "../core/v5/naming-geography.js";

const TYPES: readonly NamingGeographyEntityType[] = ["SETTLEMENT", "POI", "ROUTE"];
type Filter = { continent: string; pattern: "ALL" | NamingGeographyPattern | "AAB_FAMILY"; differencesOnly: boolean; canariesOnly: boolean };
const INITIAL: Filter = { continent: "ALL", pattern: "ALL", differencesOnly: false, canariesOnly: false };

export function NamingGeographyView({ data, showOnAtlas }: { data: NamingGeographyReadModelV1 | null; showOnAtlas: (row: NamingGeographyRow) => void }): React.JSX.Element {
  const [filters, setFilters] = useState<Record<NamingGeographyEntityType, Filter>>({ SETTLEMENT: { ...INITIAL }, POI: { ...INITIAL }, ROUTE: { ...INITIAL } });
  const continents = useMemo(() => [...new Set((data?.rows ?? []).map((row) => row.continentGroup))].sort(), [data]);
  if (!data) return <section className="panel vertical"><h2>Naming Geography</h2><p>Select a trusted V5 run to compare accepted labels.</p></section>;
  return <div className="naming-geography"><section className="cards four"><article><p>SELECTED YEAR</p><strong>{data.year}</strong><small>Effective labels only</small></article>{Object.entries(data.summaries).slice(0, 3).map(([continent, counts]) => <article key={continent}><p>{continent}</p><strong>{counts.AAA} / {counts.AAB_FAMILY} / {counts.ABC}</strong><small>AAA / AAB-family / ABC · {counts.INCOMPLETE} incomplete</small></article>)}</section>{TYPES.map((type) => {
    const filter = filters[type];
    const rows = data.rows.filter((row) => row.entityType === type).filter((row) => filter.continent === "ALL" || row.continentGroup === filter.continent).filter((row) => filter.pattern === "ALL" || filter.pattern === "AAB_FAMILY" ? filter.pattern === "ALL" || ["AAB", "ABA", "BAA"].includes(row.pattern) : row.pattern === filter.pattern).filter((row) => !filter.differencesOnly || row.pattern !== "AAA").filter((row) => !filter.canariesOnly || ["AAB", "ABA", "BAA", "ABC"].includes(row.pattern));
    return <section className="panel vertical naming-table" key={type}><div className="panel-head"><div><p className="eyebrow">{type === "SETTLEMENT" ? "SETTLEMENTS" : type === "POI" ? "POIs" : "NAMED ROUTES"}</p><h2>{rows.length} physical identities</h2></div><div className="naming-filters"><select aria-label={`${type} continent filter`} value={filter.continent} onChange={(event) => setFilters((prior) => ({ ...prior, [type]: { ...filter, continent: event.target.value } }))}><option>ALL</option>{continents.map((continent) => <option key={continent}>{continent}</option>)}</select><select aria-label={`${type} pattern filter`} value={filter.pattern} onChange={(event) => setFilters((prior) => ({ ...prior, [type]: { ...filter, pattern: event.target.value as Filter["pattern"] } }))}>{["ALL","AAA","AAB_FAMILY","AAB","ABA","BAA","ABC","INCOMPLETE"].map((pattern) => <option key={pattern}>{pattern}</option>)}</select><label><input type="checkbox" checked={filter.differencesOnly} onChange={(event) => setFilters((prior) => ({ ...prior, [type]: { ...filter, differencesOnly: event.target.checked } }))}/>SHOW DIFFERENCES ONLY</label><label><input aria-label={`${type} canaries only`} type="checkbox" checked={filter.canariesOnly} onChange={(event) => setFilters((prior) => ({ ...prior, [type]: { ...filter, canariesOnly: event.target.checked } }))}/>CANARIES ONLY</label></div></div><div className="table-wrap"><table><thead><tr><th>Physical identity</th><th>CONCORD</th><th>SCHISM</th><th>RUIN</th><th>Pattern</th><th>Audit</th><th>Atlas</th></tr></thead><tbody>{rows.map((row) => <React.Fragment key={`${row.entityType}/${row.physicalIdentity}`}><tr className="continent-heading"><td colSpan={7}>{row.continentGroup}</td></tr><tr><td><strong>{row.physicalIdentity}</strong><small>{row.secondaryReference}</small></td>{(["CONCORD","SCHISM","RUIN"] as const).map((world) => <td key={world} className={row.cells[world].cssClass ?? undefined}>{row.cells[world].display}<small>{row.cells[world].entityId}{row.cells[world].source ? ` · ${row.cells[world].source}` : ""}</small></td>)}<td>{row.pattern}</td><td>{row.comparisonAuditStatus}</td><td><button onClick={() => showOnAtlas(row)}>SHOW ON ATLAS</button></td></tr></React.Fragment>)}</tbody></table></div></section>;
  })}</div>;
}
