import { createHash } from "node:crypto";
import type { CanonicalDataV5, CausalOwnerInputsV1 } from "./config.js";
import { V5_CAUSAL_DERIVATION_VERSION, V5_MECHANICS_VERSION } from "./config.js";
import { requireHistoricalPolicyV5 } from "./historical-policies.js";
import { applyLocationMortalityV5, transferTargetedPopulationV5 } from "./population-slices.js";
import type { CausalEventV5, ConflictStageV5, ForcedDisplacementRecordV5, WorldStateV5 } from "./types.js";

export type HistoricalConflictActionV5 =
  | { actionId: string; year: number; type: "BORDER_DISPUTE" | "SKIRMISH" | "WAR"; borderRelationId: string; attackerStateId: string; defenderStateId: string }
  | { actionId: string; year: number; type: "EMBARGO"; stateAId: string; stateBId: string; affectedSettlementIds: readonly string[] }
  | { actionId: string; year: number; type: "PIRACY" | "BANDITRY"; controllerStateId: string; affectedRouteIds: readonly string[]; affectedSettlementIds: readonly string[] }
  | { actionId: string; year: number; type: "RESOURCE_SEIZURE"; resourceNodeId: string; seizingStateId: string; borderRelationId: string }
  | { actionId: string; year: number; type: "SIEGE"; attackerStateId: string; defenderStateId: string; settlementId: string; displacementDestinationSettlementId: string | null }
  | { actionId: string; year: number; type: "OCCUPATION_CAPTURE" | "CONQUEST"; settlementId: string; controllerStateId: string }
  | { actionId: string; year: number; type: "TREATY"; stateAId: string; stateBId: string; settlementId?: string; legalStateId?: string };

const digest = (parts: readonly string[]): string => createHash("sha256").update(parts.join("\u0000"), "utf8").digest("hex").slice(0, 24);
const stageFor = (type: HistoricalConflictActionV5["type"]): ConflictStageV5 => type === "BORDER_DISPUTE" ? "DISPUTE" : type === "SKIRMISH" ? "SKIRMISH" : type === "WAR" ? "WAR" : type === "SIEGE" ? "SIEGE" : type === "OCCUPATION_CAPTURE" || type === "CONQUEST" ? "OCCUPATION" : type === "TREATY" ? "PEACE" : "TENSION";

export function executeHistoricalConflictActionV5(input: { state: WorldStateV5; canonical: CanonicalDataV5; ownerInputs: CausalOwnerInputsV1; mode: "CANONICAL" | "DIAGNOSTIC"; action: HistoricalConflictActionV5 }): { state: WorldStateV5; event: CausalEventV5 } {
  const policy = requireHistoricalPolicyV5({ mode: input.mode, policies: input.ownerInputs.historicalDynamismPolicies, approvedHashes: input.ownerInputs.historicalDynamismApprovedPolicyHashes, diagnosticCandidateOptIns: input.ownerInputs.diagnosticHistoricalPolicyOptIns, policyKey: "DIPLOMACY_CONFLICT", causalOperation: `EXECUTE_${input.action.type}`, worldKey: input.state.worldKey, year: input.state.year, entityType: "CONFLICT_ACTION", entityId: input.action.actionId });
  if (input.action.year !== input.state.year) throw new Error(`Conflict action ${input.action.actionId} is scheduled for ${input.action.year}`);
  let state = input.state; let casualties = 0n; let displaced = 0n; const affectedSettlementIds: string[] = []; const affectedResourceNodeIds: string[] = []; const causeCodes: string[] = [input.action.type];
  if (input.action.type === "EMBARGO") {
    const action = input.action; state = { ...state, industries: (state.industries ?? []).map((row) => action.affectedSettlementIds.includes(row.settlementId) ? { ...row, strength: Math.max(0, row.strength - policy.embargoIndustryDamage), disruptedUntilYear: Math.max(row.disruptedUntilYear ?? state.year, state.year + policy.reviewIntervalYears) } : row), diplomaticAgreements: [...(state.diplomaticAgreements ?? []), { agreementId: `AGREEMENT_${action.actionId}`, action: "EMBARGO", stateAId: action.stateAId, stateBId: action.stateBId, startYear: state.year, endYear: null, sourceEventId: action.actionId, terms: { industryDamage: policy.embargoIndustryDamage } }] }; affectedSettlementIds.push(...action.affectedSettlementIds);
  } else if (input.action.type === "PIRACY" || input.action.type === "BANDITRY") {
    const action = input.action; state = { ...state, industries: (state.industries ?? []).map((row) => action.affectedSettlementIds.includes(row.settlementId) && (["SHIPPING", "TRANSPORT", "SMUGGLING"] as string[]).includes(row.industryType) ? { ...row, strength: Math.max(0, row.strength - policy.piracyTradeDamage), disruptedUntilYear: state.year + policy.reviewIntervalYears } : row) }; affectedSettlementIds.push(...action.affectedSettlementIds); causeCodes.push(...action.affectedRouteIds.map((row) => `ROUTE:${row}`));
  } else if (input.action.type === "RESOURCE_SEIZURE") {
    const action = input.action; if (!(state.resourceNodes ?? []).some((row) => row.resourceNodeId === action.resourceNodeId)) throw new Error(`Unknown resource node ${action.resourceNodeId}`);
    state = { ...state, worldResourceStates: (state.worldResourceStates ?? []).map((row) => row.resourceNodeId === action.resourceNodeId ? { ...row, controllerType: "STATE", controllerId: action.seizingStateId, availability: "OCCUPIED", seizedByEventId: action.actionId } : row), borderRelations: state.borderRelations.map((row) => row.borderRelationId === action.borderRelationId ? { ...row, grievance: Math.min(1000, row.grievance + policy.resourceSeizureGrievanceDelta) } : row) }; affectedResourceNodeIds.push(action.resourceNodeId);
  } else if (input.action.type === "SIEGE") {
    affectedSettlementIds.push(input.action.settlementId); const killed = applyLocationMortalityV5(state, "PUBLIC_SETTLEMENT", input.action.settlementId, policy.siegeMaximumMortalityBps, input.action.actionId); state = killed.state; casualties += killed.deaths;
    if (input.action.displacementDestinationSettlementId) { const moved = transferTargetedPopulationV5({ state, sourceLocationType: "PUBLIC_SETTLEMENT", sourceLocationId: input.action.settlementId, destinationLocationType: "PUBLIC_SETTLEMENT", destinationLocationId: input.action.displacementDestinationSettlementId, shareBps: policy.siegeMaximumDisplacementBps, sourceEventId: input.action.actionId }); state = moved.state; displaced += moved.transferred; const record: ForcedDisplacementRecordV5 = { displacementId: `DISPLACEMENT_${digest([input.action.actionId, input.action.settlementId])}`, sourceEventId: input.action.actionId, sourceLocationType: "PUBLIC_SETTLEMENT", sourceLocationId: input.action.settlementId, destinationLocationType: "PUBLIC_SETTLEMENT", destinationLocationId: input.action.displacementDestinationSettlementId, populationSliceId: moved.transferredSliceIds.join(","), population: moved.transferred, year: state.year, cause: "CONFLICT" }; state = { ...state, forcedDisplacements: [...(state.forcedDisplacements ?? []), record] }; }
  } else if (input.action.type === "OCCUPATION_CAPTURE" || input.action.type === "CONQUEST") {
    const action = input.action; const settlement = state.settlements.find((row) => row.settlementId === action.settlementId); if (!settlement) throw new Error(`Unknown Settlement ${action.settlementId}`); affectedSettlementIds.push(settlement.settlementId);
    const existing = state.settlementControlTerms?.find((row) => row.settlementId === settlement.settlementId && row.endYear === null); const terms = (state.settlementControlTerms ?? []).map((row) => row.settlementId === settlement.settlementId && row.endYear === null ? { ...row, endYear: state.year } : row);
    terms.push({ settlementControlTermId: `CONTROL_${digest([action.actionId, settlement.settlementId])}`, settlementId: settlement.settlementId, controllerStateId: action.controllerStateId, legalStateId: settlement.stateId, controlType: action.type === "CONQUEST" ? "CONQUEST" : "OCCUPATION", startYear: state.year, endYear: null, sourceEventId: action.actionId });
    state = { ...state, settlementControlTerms: terms, settlements: action.type === "CONQUEST" ? state.settlements.map((row) => row.settlementId === settlement.settlementId ? { ...row, stateId: action.controllerStateId } : row) : state.settlements }; if (existing) causeCodes.push(`CLOSED:${existing.settlementControlTermId}`);
  } else if (input.action.type === "TREATY") {
    const action = input.action; state = { ...state, diplomaticAgreements: [...(state.diplomaticAgreements ?? []), { agreementId: `AGREEMENT_${action.actionId}`, action: "TREATY", stateAId: action.stateAId, stateBId: action.stateBId, startYear: state.year, endYear: null, sourceEventId: action.actionId, terms: { settlementId: action.settlementId ?? null, legalStateId: action.legalStateId ?? null } }] };
    if (action.settlementId && action.legalStateId) { affectedSettlementIds.push(action.settlementId); state = { ...state, settlements: state.settlements.map((row) => row.settlementId === action.settlementId ? { ...row, stateId: action.legalStateId! } : row), settlementControlTerms: (state.settlementControlTerms ?? []).map((row) => row.settlementId === action.settlementId && row.endYear === null ? { ...row, endYear: state.year } : row) }; }
  }
  const participantStateIds = "attackerStateId" in input.action ? [input.action.attackerStateId, input.action.defenderStateId] : "stateAId" in input.action ? [input.action.stateAId, input.action.stateBId] : "controllerStateId" in input.action ? [input.action.controllerStateId] : "seizingStateId" in input.action ? [input.action.seizingStateId] : [];
  if (["BORDER_DISPUTE", "SKIRMISH", "WAR", "SIEGE", "OCCUPATION_CAPTURE", "CONQUEST"].includes(input.action.type)) state = { ...state, conflictEpisodes: [...(state.conflictEpisodes ?? []), { conflictEpisodeId: `CONFLICT_EPISODE_${input.action.actionId}`, relationId: "borderRelationId" in input.action ? input.action.borderRelationId : `ACTION_RELATION_${input.action.actionId}`, participantStateIds: [...participantStateIds].sort(), stage: stageFor(input.action.type), startYear: state.year, endYear: null, causeCodes, causeEventIds: [input.action.actionId], affectedSettlementIds: [...new Set(affectedSettlementIds)].sort(), affectedResourceNodeIds: [...new Set(affectedResourceNodeIds)].sort(), casualties, displaced, outcome: null }] };
  const event: CausalEventV5 = { schemaVersion: "echoes-causal-event-v5", eventId: input.action.actionId, worldKey: state.worldKey, year: state.year, phase: "DIPLOMACY", sequence: 0, eventType: `Historical${input.action.type.split("_").map((part) => part[0] + part.slice(1).toLowerCase()).join("")}`, entityType: "CONFLICT_ACTION", entityId: input.action.actionId, causeEventIds: [], mechanicsVersion: V5_MECHANICS_VERSION, causalDerivationVersion: V5_CAUSAL_DERIVATION_VERSION, keyedDecisionIdentity: null, mutations: [], payload: { action: input.action, casualties: casualties.toString(), displaced: displaced.toString(), affectedSettlementIds, affectedResourceNodeIds } };
  return { state, event };
}
