import { V5_CAUSAL_DERIVATION_VERSION, V5_MECHANICS_VERSION } from "./config.js";

export type CausalIdentifierCategory = "CANONICAL_INPUT" | "CAUSAL_OWNER_INPUT" | "MECHANICS_VARIABLE" | "DURABLE_FIELD" | "FIXED_POINT_PRIMITIVE" | "DERIVED_METRIC" | "STRUCTURAL_ENUM_OR_EVENT";
export interface CausalDerivationRegistryEntry {
  metric: string;
  range: string;
  dependencies: readonly string[];
  rule: string;
  frequency: "LOAD" | "ON_DEMAND" | "INPUT_CHANGE" | "ANNUAL" | "FIVE_YEAR" | "TRIGGERED";
  consumers: readonly string[];
  mechanicsVersion: string;
  ownerInputRequired: boolean;
}

const entry = (metric: string, range: string, dependencies: readonly string[], rule: string, frequency: CausalDerivationRegistryEntry["frequency"], consumers: readonly string[], ownerInputRequired = false): CausalDerivationRegistryEntry => ({ metric, range, dependencies, rule, frequency, consumers, mechanicsVersion: V5_CAUSAL_DERIVATION_VERSION, ownerInputRequired });

export const CAUSAL_DERIVATION_REGISTRY_V1: readonly CausalDerivationRegistryEntry[] = [
  entry("BreedFactionVector", "vector sum=1000", ["BreedFactionObject", "normalizeFactionVector"], "Normalize authoritative factionObject", "LOAD", ["Faction"]),
  entry("ResolvedBreedFaction", "WorldKey", ["BreedDominantFaction", "SovereignFaction", "sovereignTieBreak", "StructuralFactionOrder"], "Unique candidate; optional sovereign tie preference; structural fallback", "INPUT_CHANGE", ["Growth"]),
  entry("FactionCompatibility", "0..1000", ["divideRoundedAway", "clamp"], "1000 - L1 vector distance / 2", "ON_DEMAND", ["Faction mechanics"]),
  entry("SettlementPopulationFactionVector", "vector sum=1000", ["CohortTierPopulation", "BreedFactionVector", "normalizeFactionVector"], "Population-weighted Breed vectors", "INPUT_CHANGE", ["Settlement faction", "Migration"]),
  entry("SettlementDominantFaction", "WorldKey", ["SettlementPopulationFactionVector", "StructuralFactionOrder"], "Vector argmax with structural tie order", "INPUT_CHANGE", ["Growth"]),
  entry("StatePopulationFactionVector", "vector sum=1000", ["SettlementStateId", "CohortTierPopulation", "BreedFactionVector", "normalizeFactionVector"], "Population-weighted member Settlement vectors", "INPUT_CHANGE", ["Politics"]),
  entry("SupportedGovernment", "GovernmentFormId", ["StatePopulationFactionVector", "GovernmentDoctrineVector", "FactionCompatibility"], "Maximum doctrine compatibility; stable government ID tie", "FIVE_YEAR", ["Government", "Secession"]),
  entry("GovernmentDoctrineVector", "vector sum=1000", ["GovernmentPrototype", "normalizeFactionVector"], "Canonical government doctrine lookup", "INPUT_CHANGE", ["State faction", "Legitimacy"]),
  entry("ActualGovernmentCompatibility", "0..1000", ["StateActualGovernment", "StatePopulationFactionVector", "GovernmentDoctrineVector", "FactionCompatibility"], "Population/doctrine compatibility", "FIVE_YEAR", ["Government", "Legitimacy"]),
  entry("InstitutionControlVector", "vector sum=1000", ["OfficeInstitutionId", "OfficeTerm", "PoliticalPersonBreedId", "PoliticalPersonFamilyId", "FamilyFactionAffinity", "BreedFactionVector", "OfficePower", "GovernmentDoctrineVector", "normalizedVectorWeightedMean"], "Office-power-weight holder Family/Breed vectors; doctrine fallback", "INPUT_CHANGE", ["State faction", "Access"]),
  entry("RulingCoalitionVector", "vector sum=1000", ["InstitutionControlVector", "OfficeApex"], "Institution control restricted to apex Offices", "INPUT_CHANGE", ["State faction", "Legitimacy"]),
  entry("RulingCoalitionSupport", "0..1000", ["RulingCoalitionVector", "StatePopulationFactionVector", "FactionCompatibility", "FamilyPrestige", "weightedMean"], "Compatibility 7000 + ruling Family prestige 3000; no Family prestige=500", "FIVE_YEAR", ["Legitimacy"]),
  entry("StateFactionTargetVector", "vector sum=1000", ["StatePopulationFactionVector", "GovernmentDoctrineVector", "RulingCoalitionVector", "InstitutionControlVector", "stateFactionWeights", "normalizedVectorWeightedMean"], "5000/2500/1500/1000 layer mean", "FIVE_YEAR", ["State faction writer"]),
  entry("SettlementProsperity", "0..1000", ["CohortTierPopulation", "CohortTierProsperity", "divideRoundedAway"], "Population-weight all tier prosperity", "INPUT_CHANGE", ["Economy"]),
  entry("SettlementHighProsperity", "0..1000", ["CohortTierPopulation", "CohortTierProsperity", "divideRoundedAway"], "HIGH-population-weight prosperity; empty=0", "INPUT_CHANGE", ["Capital", "Family"]),
  entry("ProsperityDispersion", "0..1000", ["SettlementProsperity", "CohortTierPopulation", "CohortTierProsperity", "divideRoundedAway", "clamp"], "Twice population-weight absolute deviation", "INPUT_CHANGE", ["Inequality"]),
  entry("OwnershipConcentration", "0..1000", ["OwnershipStake", "OrganizationStatus", "divideRoundedAway", "clamp"], "HHI of active non-DIFFUSE ownership shares", "INPUT_CHANGE", ["Inequality", "Organizations"]),
  entry("Inequality", "0..1000", ["ProsperityDispersion", "OwnershipConcentration", "weightedMean"], "Dispersion 6000 + concentration 4000", "FIVE_YEAR", ["Unrest", "Social"]),
  entry("OfficeFillRatio", "0..1000", ["OfficeMandatory", "OfficePower", "OfficeTerm", "ratioScore"], "Filled mandatory power / total mandatory power", "INPUT_CHANGE", ["Institution effectiveness"]),
  entry("InstitutionContinuity", "0..1000", ["StateLastGovernmentTransitionYear", "CurrentYear", "institutionContinuityMaturityYears", "ratioScore"], "Years since transition / maturity years", "FIVE_YEAR", ["Institution effectiveness"]),
  entry("InstitutionEffectiveness", "0..1000", ["OfficeFillRatio", "InstitutionContinuity", "weightedMean"], "Fill 6000 + continuity 4000", "FIVE_YEAR", ["Access", "Enforcement", "Capacity"]),
  entry("InstitutionalAccess", "0..1000", ["GovernmentPrototype", "SettlementPopulationFactionVector", "InstitutionControlVector", "OwnershipConcentration", "FactionCompatibility", "weightedMean"], "Franchise 4000 + population/control compatibility 4000 + inverse concentration 2000", "FIVE_YEAR", ["Social", "Crime", "Office"]),
  entry("PoliticalExclusion", "0..1000", ["InstitutionalAccess"], "1000 - access", "INPUT_CHANGE", ["Crime", "Secession", "Unrest"]),
  entry("IndustryMean", "0..1000", ["SettlementSectorStrength", "divideRoundedAway"], "Arithmetic mean of five sectors", "INPUT_CHANGE", ["Economy", "Capacity"]),
  entry("IndustryBreadth", "0..1000", ["SettlementSectorStrength", "ratioScore"], "1000 - normalized sector HHI; zero total=0", "INPUT_CHANGE", ["Social"]),
  entry("LaborCapacity", "0..1000", ["CohortTierPopulation", "ratioScore"], "LOW+MID share", "INPUT_CHANGE", ["Industry"]),
  entry("KnowledgeCapacity", "0..1000", ["CohortTierPopulation", "ratioScore"], "HIGH+MID share", "INPUT_CHANGE", ["Industry"]),
  entry("LocalFamilyWealth", "0..1000", ["FamilyStatus", "FamilyHomeSettlementId", "FamilyWealth", "FamilyInfluence", "divideRoundedAway"], "Influence-weight ACTIVE Family wealth; denominator zero=0", "INPUT_CHANGE", ["Capital"]),
  entry("LocalOrganizationWealth", "0..1000", ["OrganizationStatus", "OrganizationHomeSettlementId", "OrganizationWealth", "divideRoundedAway"], "Arithmetic mean ACTIVE Organization wealth; empty=0", "INPUT_CHANGE", ["Capital"]),
  entry("CapitalAvailability", "0..1000", ["SettlementHighProsperity", "LocalFamilyWealth", "LocalOrganizationWealth", "weightedMean"], "HIGH prosperity 5000 + Family wealth 3000 + Organization wealth 2000", "FIVE_YEAR", ["Industry", "Corporations"]),
  entry("TradeAccess", "0..1000", ["RegionAdjacency", "SettlementRegionId", "CohortTierPopulation", "migrationMaximumHops", "ratioScore"], "Directed shortest Region hops; distance-weight reachable population / all other population at maximum weight", "FIVE_YEAR", ["Industry", "Organizations"]),
  entry("SupportedEconomicForm", "EconomicFormId", ["CohortTierPopulation", "BreedOwnershipMode", "BreedAllocationMode", "EconomicFormMapping"], "For every occupied Settlement, sum exact population by authoritative ownership/allocation values; score each canonical mapping by matching ownership population plus matching allocation population; choose maximum then stable economicForm ID", "INPUT_CHANGE", ["Read model", "Naming"]),
  entry("SectorTerrainFit", "0..1000", ["SiteTerrain", "SectorTerrainLookup"], "Canonical lookup; missing=500", "INPUT_CHANGE", ["Industry", "Founding"]),
  entry("SectorStrengthTarget", "0..1000", ["LaborCapacity", "KnowledgeCapacity", "CapitalAvailability", "TradeAccess", "SectorTerrainFit", "sectorStrengthWeights", "weightedMean"], "Sector-specific registered five-input mean", "FIVE_YEAR", ["Industry writer"]),
  entry("EconomicStrain", "0..1000", ["SettlementProsperity", "IndustryMean", "weightedMean"], "Inverse prosperity 6000 + inverse industry 4000", "FIVE_YEAR", ["Social", "Unrest"]),
  entry("SettlementStability", "0..1000", ["SettlementUnrest"], "1000 - unrest", "INPUT_CHANGE", ["Economy", "Migration"]),
  entry("LocalOpportunity", "0..1000", ["IndustryMean", "SettlementProsperity", "InstitutionalAccess", "SettlementStability", "weightedMean"], "Industry 4000 + prosperity 3500 + access 1500 + stability 1000", "FIVE_YEAR", ["Migration", "Family"]),
  entry("MarketAllocationCompatibility", "0..1000", ["BreedFactionVector", "StateFactionAffinity", "InstitutionalAccess", "InstitutionControlVector", "FactionCompatibility", "weightedMean"], "Breed/State 5000 + access 3000 + Breed/institution 2000", "FIVE_YEAR", ["Prosperity"]),
  entry("TierProsperityTarget", "0..1000", ["LocalOpportunity", "TierProsperityBaseline", "MarketAllocationCompatibility", "SettlementStability", "weightedMean"], "Opportunity 3500 + baseline 2500 + compatibility 2500 + stability 1500", "FIVE_YEAR", ["Prosperity writer"]),
  entry("RecentMigrationIntensity", "0..1000", ["TimedCondition", "ratioScore"], "Absolute net migration / pre-migration Settlement population", "FIVE_YEAR", ["Disruption", "Class"]),
  entry("DisruptionPressure", "0..1000", ["RecentMigrationIntensity", "TimedCondition"], "Maximum recent migration and active disruption condition", "FIVE_YEAR", ["Unrest"]),
  entry("StateDisruptionPressure", "0..1000", ["DisruptionPressure", "SettlementStateId", "CohortTierPopulation", "divideRoundedAway"], "State-population-weight Settlement disruption", "FIVE_YEAR", ["Crisis"]),
  entry("StateCrisisPressure", "0..1000", ["StateDisruptionPressure", "TimedCondition"], "Maximum disruption and active State crisis; rebellion/coup condition=1000", "FIVE_YEAR", ["Government"]),
  entry("TerrainCompatibility", "0..1000", ["BreedTerrain", "SiteTerrain", "TerrainPolicy"], "Approved exact/partial/mismatch/unknown policy; food excluded", "ON_DEMAND", ["Migration", "Founding"], true),
  entry("ClassDistribution", "exact counts", ["CohortTierPopulation", "ClassPolicy", "largestRemainder"], "Approved tier/context weights apportioned exactly", "ON_DEMAND", ["Shocks", "Offices", "Family"], true),
  entry("SocialEquilibriumTarget", "exact capacities", ["SettlementProsperity", "IndustryBreadth", "InstitutionalAccess", "Inequality", "EconomicStrain", "socialCapacityCoefficients", "scaled", "largestRemainder"], "Settlement-level capacity weights", "FIVE_YEAR", ["Mobility"]),
  entry("MobilityCandidateScore", "0..1000", ["CohortTierProsperity", "LocalOpportunity", "InstitutionalAccess", "SettlementUnrest", "mobilityScoreWeights", "weightedMean"], "Directional upward score; downward=1000-upward", "FIVE_YEAR", ["Mobility"]),
  entry("MobilityAggregateQuotas", "exact flows", ["SocialEquilibriumTarget", "CohortTierPopulation", "socialMobilityMaximumBps", "MobilityCandidateScore", "largestRemainder"], "Adjacent constrained transport in structural order", "FIVE_YEAR", ["Tier transfers"]),
  entry("MigrationEconomicDisadvantage", "0..1000", ["LocalOpportunity", "CohortTierProsperity", "clamp"], "Positive best opportunity minus current prosperity", "FIVE_YEAR", ["Migration push"]),
  entry("MigrationPush", "0..1000", ["FactionCompatibility", "MigrationEconomicDisadvantage", "SettlementUnrest", "migrationPushWeights", "weightedMean"], "Mismatch 4000 + disadvantage 3500 + unrest 2500", "FIVE_YEAR", ["Migration", "Founding"]),
  entry("DestinationAttractiveness", "0..1000", ["LocalOpportunity", "FactionCompatibility", "SettlementStability", "TerrainCompatibility", "migrationAttractivenessWeights", "weightedMean"], "Opportunity 3500 + faction 3000 + stability 2000 + terrain 1500", "FIVE_YEAR", ["Migration"]),
  entry("CanonicalSiteQuality", "0..1000", ["SiteQuality", "foundingSiteQualityFallback"], "Canonical quality; missing=fallback", "ON_DEMAND", ["Founding"]),
  entry("FoundingDistanceCloseness", "0..1000", ["RegionAdjacency", "migrationMaximumHops", "divideRoundedAway"], "(maximumHops+1-hops)*1000/(maximumHops+1)", "FIVE_YEAR", ["Founding"]),
  entry("FoundingSiteScore", "0..1000", ["TerrainCompatibility", "CanonicalSiteQuality", "FoundingDistanceCloseness", "foundingSiteScoreWeights", "weightedMean"], "Terrain 5000 + quality 3000 + distance 2000", "FIVE_YEAR", ["Founding"]),
  entry("FoundingInitialUnrest", "0..1000", ["SettlementUnrest", "CohortTierPopulation", "divideRoundedAway"], "Founder-population-weight source Settlement unrest; no founders=0", "TRIGGERED", ["Settlement founding"]),
  entry("FoundingInitialSectorStrength", "0..1000", ["industryInitialFallback", "SectorTerrainFit", "weightedMean"], "Industry fallback 5000 + Site sector terrain fit 5000", "TRIGGERED", ["Settlement founding"]),
  entry("StateAdjacency", "unordered State pairs", ["SettlementStateId", "SettlementRegionId", "RegionAdjacency"], "Same Region or either directed Region edge", "INPUT_CHANGE", ["Borders"]),
  entry("StateUnrest", "0..1000", ["SettlementUnrest", "SettlementStateId", "CohortTierPopulation", "divideRoundedAway"], "Population-weight member Settlement unrest", "INPUT_CHANGE", ["Politics", "Conflict"]),
  entry("BorderExposure", "0..1000", ["BorderActive", "BorderTension"], "Maximum active-border tension; none=0", "INPUT_CHANGE", ["Unrest"]),
  entry("StateExhaustion", "0..1000", ["BorderActive", "BorderExhaustion"], "Maximum active-border exhaustion; none=0", "INPUT_CHANGE", ["Unrest"]),
  entry("StateGrievance", "0..1000", ["BorderActive", "BorderGrievance"], "Maximum active-border grievance; none=0", "INPUT_CHANGE", ["Unrest"]),
  entry("BorderStateUnrest", "0..1000", ["StateUnrest", "divideRoundedAway"], "Rounded mean of both States", "FIVE_YEAR", ["Conflict"]),
  entry("MaterialUnrestPressure", "0..1000", ["EconomicStrain", "Inequality", "weightedMean"], "Economic strain 6000 + inequality 4000", "FIVE_YEAR", ["Unrest"]),
  entry("PoliticalUnrestPressure", "0..1000", ["PoliticalExclusion", "FactionCompatibility", "ActualGovernmentCompatibility", "weightedMean"], "Exclusion 5000 + State-faction mismatch 3000 + government mismatch 2000", "FIVE_YEAR", ["Unrest"]),
  entry("ConflictGrievancePressure", "0..1000", ["BorderExposure", "StateExhaustion", "StateGrievance", "weightedMean"], "Exposure 4000 + exhaustion 3000 + grievance 3000", "FIVE_YEAR", ["Unrest"]),
  entry("UnrestTarget", "0..1000", ["MaterialUnrestPressure", "PoliticalUnrestPressure", "DisruptionPressure", "ConflictGrievancePressure", "weightedMean"], "Material 3000 + political 3000 + disruption 2000 + conflict/grievance 2000", "FIVE_YEAR", ["Unrest writer"]),
  entry("RecentOutcomeScore", "0..1000", ["TimedCondition", "clamp"], "500 plus the sum of active typed State outcome-condition deltas, clamped", "FIVE_YEAR", ["Legitimacy"]),
  entry("TargetLegitimacy", "0..1000", ["ActualGovernmentCompatibility", "RulingCoalitionSupport", "InstitutionEffectiveness", "StateUnrest", "RecentOutcomeScore", "legitimacyWeights", "weightedMean"], "3000/2000/2000/2000/1000", "FIVE_YEAR", ["Legitimacy writer"]),
  entry("GovernmentTransitionPressure", "0..1000", ["ActualGovernmentCompatibility", "StateLegitimacy", "StateUnrest", "StateCrisisPressure", "governmentTransitionWeights", "weightedMean"], "Mismatch 3500 + inverse legitimacy 3000 + unrest 2500 + crisis 1000", "FIVE_YEAR", ["Government"]),
  entry("EligibleAggregatePopulation", ">=0 integer", ["CohortTierPopulation", "ClassDistribution", "SelectionRule"], "Exact aggregate source population remaining after SelectionRule scope, tier, class, faction, and lineage filters", "TRIGGERED", ["Person materialization"]),
  entry("LocalPoliticalSupport", "0..1000", ["SettlementPopulationFactionVector", "StateFactionAffinity", "FactionCompatibility"], "Faction compatibility between source Settlement population and current State", "TRIGGERED", ["Person materialization", "Office selection"]),
  entry("PoliticalPersonSourceScore", "0..1000", ["EligibleAggregatePopulation", "FactionCompatibility", "ClassDistribution", "LocalPoliticalSupport", "SelectionRule", "weightedMean"], "Population 4000 + faction fit 2500 + class fit 1500 + local support 1500 + rule fit 500", "TRIGGERED", ["Person materialization"]),
  entry("OfficeCandidateScore", "0..1000", ["FactionCompatibility", "ClassDistribution", "LocalPoliticalSupport", "FamilyOfficePowerShare", "InstitutionEffectiveness", "StateLegitimacy", "SelectionRule", "weightedMean"], "SelectionRule weights candidate faction, class, local support, lineage, and rule-specific fit; weights total 10000", "TRIGGERED", ["Office selection"]),
  entry("FamilyFormationPressure", "0..1000", ["SettlementHighProsperity", "CohortTierPopulation", "ClassDistribution", "LocalOpportunity", "InstitutionalAccess", "weightedMean"], "HIGH prosperity 2500 + HIGH share 2000 + NOBILITY share 2500 + opportunity 1500 + access 1500; only historically relevant untracked people may promote", "FIVE_YEAR", ["Family promotion"]),
  entry("FamilyOwnershipValue", "0..1000", ["OwnershipStake", "OrganizationStatus", "OrganizationWealth", "divideRoundedAway", "clamp"], "Sum active non-DIFFUSE Family ownership share times Organization wealth divided by 10000, clamped", "INPUT_CHANGE", ["Family wealth"]),
  entry("FamilyOwnershipControl", "0..1000", ["OwnershipStake", "divideRoundedAway", "clamp"], "Sum active non-DIFFUSE Family control BPS divided by 10, clamped", "INPUT_CHANGE", ["Family influence"]),
  entry("FamilyOfficePowerShare", "0..1000", ["FamilyHomeSettlementId", "SettlementStateId", "PoliticalPersonFamilyId", "OfficeTerm", "OfficePower", "ratioScore"], "Family-held Office power divided by total Office power in home State", "INPUT_CHANGE", ["Family influence", "Networks"]),
  entry("FamilyNetworkStrength", "0..1000", ["FamilyRelation", "PersonRelation", "OfficeTerm", "OwnershipStake", "weightedMean"], "Strongest alliance 4000 + any kin Office 3500 + any shared Organization control 2500", "INPUT_CHANGE", ["Family influence", "Organizations"]),
  entry("FamilyInteractionSignal", "0..1000 per signal", ["FamilyRelation", "PersonRelation", "OfficeTerm", "OwnershipStake", "ActiveConflict"], "Typed concrete shared-control, coalition, marriage, succession, war, Office defeat, ownership displacement, or betrayal signal", "INPUT_CHANGE", ["Family relation pressure"]),
  entry("FamilyEconomicBase", "0..1000", ["FamilyOwnershipValue", "SettlementHighProsperity", "LocalOpportunity", "weightedMean"], "Ownership 5500 + HIGH prosperity 3000 + opportunity 1500", "FIVE_YEAR", ["Family wealth"]),
  entry("FamilyPoliticalBase", "0..1000", ["FamilyOfficePowerShare", "FamilyOwnershipControl", "FamilyNetworkStrength", "FamilyPrestige", "weightedMean"], "Office 4500 + control 2500 + network 1500 + prestige 1500", "FIVE_YEAR", ["Family influence"]),
  entry("FamilyFactionTarget", "vector sum=1000", ["SettlementPopulationFactionVector", "StateFactionAffinity", "FamilyRelation", "FamilyFactionAffinity", "normalizedVectorWeightedMean"], "Home population 5000 + State 3000 + active-allied Family mean 2000; current Family vector is ally fallback", "FIVE_YEAR", ["Family faction writer"]),
  entry("FamilyAlliancePressure", "0..1000", ["FamilyInteractionSignal", "clamp"], "Sum concrete alliance signals", "FIVE_YEAR", ["FamilyRelation"]),
  entry("FamilyRivalryPressure", "0..1000", ["FamilyInteractionSignal", "clamp"], "Sum concrete rivalry signals", "FIVE_YEAR", ["FamilyRelation"]),
  entry("EnforcementStrength", "0..1000", ["InstitutionEffectiveness", "StateLegitimacy", "SettlementStability", "weightedMean"], "Institutions 4000 + legitimacy 3500 + stability 2500", "FIVE_YEAR", ["Crime"]),
  entry("SectorRentScore", "0..1000", ["SettlementSectorStrength", "OwnershipConcentration", "weightedMean"], "Sector strength 7000 + concentration 3000", "FIVE_YEAR", ["Organizations"]),
  entry("CorporateFormationPressure", "0..1000", ["SettlementSectorStrength", "CapitalAvailability", "TradeAccess", "EnforcementStrength", "OwnershipConcentration", "weightedMean"], "Sector 3000 + capital 3000 + trade 1500 + enforcement 1000 + concentration 1500", "FIVE_YEAR", ["Organization formation"]),
  entry("CrimeFormationPressure", "0..1000", ["SectorRentScore", "PoliticalExclusion", "EnforcementStrength", "SettlementUnrest", "FamilyNetworkStrength", "weightedMean"], "Rents 2500 + exclusion 2500 + inverse enforcement 2500 + unrest 1500 + Family network 1000", "FIVE_YEAR", ["Organization formation"]),
  entry("OrganizationControllerCandidateScore", "0..1000", ["FamilyWealth", "FamilyInfluence", "FamilyNetworkStrength", "FamilyOfficePowerShare", "FactionCompatibility", "weightedMean"], "Corporation: wealth 3500/influence 1500/network 1000/Office 1500/local fit 2500; crime: network 3000/wealth 2000/influence 2000/Office 1500/local fit 1500", "TRIGGERED", ["Organization ownership"]),
  entry("OrganizationControlConcentration", "0..1000", ["OwnershipStake", "divideRoundedAway"], "Maximum active non-DIFFUSE control BPS / 10; none=0", "INPUT_CHANGE", ["Organization influence"]),
  entry("OrganizationPoliticalCapture", "0..1000", ["OwnershipStake", "OfficeTerm", "OfficePower", "PoliticalPersonFamilyId", "divideRoundedAway"], "Non-DIFFUSE Person/Family control-weighted Office power", "INPUT_CHANGE", ["Organization influence"]),
  entry("OrganizationPerformanceTarget", "0..1000", ["SettlementSectorStrength", "CapitalAvailability", "TradeAccess", "EnforcementStrength", "PoliticalExclusion", "FamilyNetworkStrength", "SettlementUnrest", "OwnershipConcentration", "weightedMean"], "Type-specific registered common-mechanics formula", "FIVE_YEAR", ["Organization wealth"]),
  entry("OrganizationInfluenceTarget", "0..1000", ["OrganizationWealth", "OrganizationControlConcentration", "OrganizationPoliticalCapture", "weightedMean"], "Wealth 4500 + concentration 3000 + capture 2500", "FIVE_YEAR", ["Organization influence"]),
  entry("OrganizationSurvivalScore", "0..1000", ["OrganizationWealth", "OrganizationInfluence", "OrganizationPerformanceTarget", "weightedMean"], "Wealth 5000 + influence 2500 + performance 2500", "FIVE_YEAR", ["Organization lifecycle"]),
  entry("SecessionGroupPopulation", ">=0 integer", ["SettlementStateId", "CohortTierPopulation"], "Sum exact populations of the connected qualifying Settlement component", "FIVE_YEAR", ["Secession eligibility"]),
  entry("SecessionGroupUnrest", "0..1000", ["SettlementUnrest", "CohortTierPopulation", "divideRoundedAway"], "Candidate-population-weight Settlement unrest", "FIVE_YEAR", ["Secession pressure"]),
  entry("SecessionGroupFactionVector", "vector sum=1000", ["SettlementPopulationFactionVector", "CohortTierPopulation", "normalizedVectorWeightedMean"], "Candidate-population-weight Settlement population faction vectors", "FIVE_YEAR", ["Secession mismatch"]),
  entry("SecessionFactionMismatch", "0..1000", ["SecessionGroupFactionVector", "StateFactionAffinity", "FactionCompatibility"], "1000 minus candidate/parent-State faction compatibility", "FIVE_YEAR", ["Secession eligibility", "Secession pressure"]),
  entry("SecessionGroupPoliticalExclusion", "0..1000", ["PoliticalExclusion", "CohortTierPopulation", "divideRoundedAway"], "Candidate-population-weight Settlement political exclusion", "FIVE_YEAR", ["Secession pressure"]),
  entry("SecessionPressure", "0..1000", ["SecessionGroupUnrest", "SecessionFactionMismatch", "SecessionGroupPoliticalExclusion", "StateLegitimacy", "weightedMean"], "Unrest 4000 + mismatch 3500 + exclusion 1500 + inverse legitimacy 1000", "FIVE_YEAR", ["Secession"]),
  entry("FactionHostility", "0..1000", ["StateFactionAffinity", "FactionCompatibility"], "1000 minus the two State faction-vector compatibility", "FIVE_YEAR", ["Conflict"]),
  entry("TerritorialDisputePressure", "0..1000", ["BorderTerritorialClaim"], "Current durable border territorial claim", "FIVE_YEAR", ["Conflict"]),
  entry("BorderEconomicPressure", "0..1000", ["EconomicStrain", "LocalOpportunity", "SettlementStateId", "CohortTierPopulation", "weightedMean"], "Mean border strain 5000 + opportunity difference 5000", "FIVE_YEAR", ["Conflict"]),
  entry("StatePopulationScale", "0..1000", ["CohortTierPopulation", "SettlementStateId", "conflictStatePopulationReference", "ratioScore"], "State population / reference", "FIVE_YEAR", ["Capacity"]),
  entry("StateIndustryStrength", "0..1000", ["IndustryMean", "SettlementStateId", "CohortTierPopulation", "divideRoundedAway"], "State-population-weight Settlement industry mean", "FIVE_YEAR", ["Capacity"]),
  entry("StateCapacity", "0..1000", ["StateIndustryStrength", "InstitutionEffectiveness", "StateLegitimacy", "StateUnrest", "StatePopulationScale", "weightedMean"], "2500/2500/2000/1500/1500", "FIVE_YEAR", ["War outcomes"]),
  entry("ConflictPressure", "0..1000", ["FactionCompatibility", "BorderTerritorialClaim", "BorderEconomicPressure", "BorderStateUnrest", "BorderGrievance", "weightedMean"], "Hostility 3000 + territory 2500 + economics 2000 + unrest 1500 + grievance 1000", "FIVE_YEAR", ["Border tension"]),
  entry("PeacePressure", "0..1000", ["BorderExhaustion", "BorderTension", "weightedMean"], "Exhaustion 7000 + inverse tension 3000", "FIVE_YEAR", ["Peace"]),
  entry("ConflictAge", "0..1000", ["ActiveConflict", "CurrentYear", "clamp"], "Clamp((currentYear-declaredYear)*100,0,1000)", "ANNUAL", ["War intensity"]),
  entry("ConflictEpisodeIntensity", "0..1000", ["BorderTension", "BorderExhaustion", "ConflictAge", "WAR_EPISODE_INTENSITY", "weightedMean"], "Tension 4000 + exhaustion 2000 + age 2000 + keyed draw 2000", "ANNUAL", ["War effects"], true),
  entry("ConflictEpisodeBalance", "-1000..1000", ["StateCapacity", "WAR_EPISODE_OUTCOME", "clamp"], "Attacker minus defender capacity plus keyed [-200,200] swing", "ANNUAL", ["War effects"], true),
  entry("ShockResolvedTargetSet", "stable IDs", ["ShockDefinition", "PriorDurableState"], "Resolve entity scopes at transaction start; execute ordered effects on fixed targets", "TRIGGERED", ["Typed effects"], true),
];

export interface DurableWriterRegistryEntry { field: string; initialSource: string; writers: readonly string[]; rule: string; range: string; consumers: readonly string[]; }
export const DURABLE_WRITER_REGISTRY_V1: readonly DurableWriterRegistryEntry[] = [
  { field: "CohortTierPopulation", initialSource: "YearZeroAllocation", writers: ["NaturalDemography", "PopulationLossEffect", "ForcedMigrationEffect", "TierTransferEffect", "FoundingTransfer"], rule: "Exact integer accounting; only demography creates population", range: ">=0 bigint", consumers: ["All population mechanics"] },
  { field: "CohortTierProsperity", initialSource: "TierProsperityInitial", writers: ["ProsperityReview", "ProsperityEffect", "TierTransferMerge", "MigrationTransferMerge"], rule: "Inertial target or exact population-weight merge", range: "0..1000", consumers: ["Economy", "Mobility", "Migration"] },
  { field: "SettlementSiteId", initialSource: "BootstrapOrSettlementFounded", writers: ["Bootstrap", "SettlementFounded"], rule: "Canonical Site ID; immutable afterward", range: "SiteId", consumers: ["Topology", "Terrain"] },
  { field: "SettlementRegionId", initialSource: "CanonicalSite", writers: ["Bootstrap", "SettlementFounded"], rule: "Copied from authoritative Site; immutable afterward", range: "RegionId", consumers: ["Topology"] },
  { field: "SettlementFoundedYear", initialSource: "CanonicalOrCreationYear", writers: ["Bootstrap", "SettlementFounded"], rule: "Immutable afterward", range: "year", consumers: ["History"] },
  { field: "SettlementStateId", initialSource: "BootstrapOrFoundingAssignment", writers: ["Bootstrap", "SettlementFounded", "StateMembershipEffect"], rule: "Membership transfer does not move population", range: "StateId", consumers: ["State derivations"] },
  { field: "SettlementUnrest", initialSource: "CanonicalOrZeroOrFoundingMean", writers: ["UnrestReview", "UnrestEffect"], rule: "Inertial target plus typed deltas", range: "0..1000", consumers: ["Migration", "Politics", "Conflict"] },
  { field: "SettlementSectorStrength", initialSource: "CanonicalOrFoundingRule", writers: ["IndustryReview", "IndustryDamageEffect"], rule: "Inertial target minus typed damage", range: "0..1000", consumers: ["Economy", "Organizations", "Conflict"] },
  { field: "StateIdentity", initialSource: "CanonicalOrSecession", writers: ["Bootstrap", "StateSecessionTransaction"], rule: "Stable ID; never renamed or reused", range: "StateId", consumers: ["All State mechanics"] },
  { field: "StateActualGovernment", initialSource: "CanonicalOrSupportedGovernment", writers: ["GovernmentTransitionTransaction"], rule: "Routine or typed immediate transition", range: "GovernmentFormId", consumers: ["Politics", "Institutions"] },
  { field: "StateGovernmentReviewPersistence", initialSource: "0", writers: ["RoutineGovernmentReview", "GovernmentTransitionTransaction"], rule: "Reset below threshold/cooldown/transition; increment qualifying review", range: ">=0 integer", consumers: ["Government"] },
  { field: "StateLastGovernmentTransitionYear", initialSource: "CanonicalOrBootstrapYear", writers: ["GovernmentTransitionTransaction"], rule: "Set current year atomically for routine/immediate transition", range: "year", consumers: ["InstitutionContinuity"] },
  { field: "StateRoutineTransitionCooldown", initialSource: "0OrCanonical", writers: ["GovernmentTransitionTransaction"], rule: "Transition year + cooldown", range: "year", consumers: ["Government"] },
  { field: "StateFactionAffinityAndDominant", initialSource: "YearZeroTarget", writers: ["StateFactionReview", "FactionAffinityEffect"], rule: "Inertia, exact normalization, dominant hysteresis", range: "vector sum=1000/WorldKey", consumers: ["Politics", "Conflict"] },
  { field: "StateLegitimacy", initialSource: "CanonicalOrTarget", writers: ["LegitimacyReview", "LegitimacyEffect"], rule: "Inertial target plus typed delta", range: "0..1000", consumers: ["Government", "Organizations", "Conflict"] },
  { field: "FamilyIdentityAndHome", initialSource: "CanonicalOrFormation", writers: ["Bootstrap", "FamilyFormationTransaction"], rule: "Stable ID, founder Breed, home, and founding year; immutable", range: "IDs/year", consumers: ["Family mechanics"] },
  { field: "FamilyWealth", initialSource: "CanonicalOrFormation", writers: ["FamilyReview", "FamilyPowerEffect"], rule: "FamilyEconomicBase with familyScoreInertiaBps plus typed delta", range: "0..1000", consumers: ["Capital", "Organizations"] },
  { field: "FamilyInfluence", initialSource: "CanonicalOrFormation", writers: ["FamilyReview", "FamilyPowerEffect"], rule: "FamilyPoliticalBase with familyScoreInertiaBps plus typed delta", range: "0..1000", consumers: ["Politics", "Organizations"] },
  { field: "FamilyPrestige", initialSource: "CanonicalOr500", writers: ["FamilyReview", "FamilyPowerEffect"], rule: "Office power 6000 plus network 4000 target with inertia, plus typed delta", range: "0..1000", consumers: ["Politics"] },
  { field: "FamilyFactionAffinity", initialSource: "FounderBreedOrCanonical", writers: ["FamilyReview"], rule: "FamilyFactionTarget with familyScoreInertiaBps and exact normalization", range: "vector sum=1000", consumers: ["Politics", "Organizations"] },
  { field: "FamilyStatus", initialSource: "ACTIVE", writers: ["FamilyStatusEffect"], rule: "Validated ACTIVE to EXTINCT only; no V5 revival", range: "ACTIVE|EXTINCT", consumers: ["Family", "Read models"] },
  { field: "FamilyExtinctionYear", initialSource: "null", writers: ["FamilyStatusEffect"], rule: "Set on validated extinction and never cleared", range: "year|null", consumers: ["History"] },
  { field: "PoliticalPersonTemporalState", initialSource: "CanonicalOrMaterialization", writers: ["PersonCreation", "PoliticalPersonDeathEffect", "RetirementEvent", "DisqualificationEvent"], rule: "Indexed temporal boundaries; no annual biology", range: "years/null", consumers: ["Office eligibility"] },
  { field: "PoliticalPersonIdentityContext", initialSource: "CanonicalOrMaterialization", writers: ["Bootstrap", "PersonCreation"], rule: "Stable identity, Breed, origin, tier/class source, and optional Family; naming-independent", range: "IDs/context", consumers: ["Office eligibility", "Narrative"] },
  { field: "PoliticalPersonFactionAffinity", initialSource: "PersonCreation", writers: ["PersonCreation", "PoliticalPersonAlignmentChanged"], rule: "Explicit normalized person alignment; never inferred at read time from Family, Breed, constituency, selector, or World", range: "vector sum=1000", consumers: ["Office selection", "Chamber read model", "PostgreSQL projection"] },
  { field: "OrganizationIdentityContext", initialSource: "CanonicalOrFormation", writers: ["Bootstrap", "OrganizationFormationTransaction"], rule: "Stable type, sector, home, founder, and formation year", range: "IDs/enum/year", consumers: ["Organization mechanics"] },
  { field: "OrganizationWealth", initialSource: "CanonicalOrFormationDefault", writers: ["OrganizationReview"], rule: "OrganizationPerformanceTarget with organizationScoreInertiaBps", range: "0..1000", consumers: ["Lifecycle", "Capital"] },
  { field: "OrganizationInfluence", initialSource: "CanonicalOrFormationDefault", writers: ["OrganizationReview"], rule: "OrganizationInfluenceTarget with organizationScoreInertiaBps", range: "0..1000", consumers: ["Lifecycle", "Politics"] },
  { field: "OrganizationStatus", initialSource: "ACTIVE", writers: ["OrganizationSurvivalReview"], rule: "ACTIVE to DECLINING after one bad review; return ACTIVE if recovered; DISSOLVED after required consecutive bad reviews; no reactivation", range: "ACTIVE|DECLINING|DISSOLVED", consumers: ["Organizations", "Read models"] },
  { field: "OrganizationSurvivalPersistence", initialSource: "0", writers: ["OrganizationSurvivalReview"], rule: "Reset on recovery; increment below threshold", range: ">=0 integer", consumers: ["Lifecycle"] },
  { field: "OrganizationDissolutionYear", initialSource: "null", writers: ["OrganizationSurvivalReview"], rule: "Set on dissolution and never cleared", range: "year|null", consumers: ["History"] },
  { field: "Institution", initialSource: "CanonicalOrGovernmentBootstrap", writers: ["Bootstrap", "GovernmentTransitionTransaction", "StateSecessionTransaction", "SettlementFounded"], rule: "Office authority container; dissolved rather than deleted", range: "typed entity", consumers: ["Offices", "Politics"] },
  { field: "Office", initialSource: "CanonicalOrGovernmentBootstrap", writers: ["Bootstrap", "GovernmentTransitionTransaction", "StateSecessionTransaction", "SettlementFounded"], rule: "Office.institutionId is sole Institution relation authority", range: "typed entity", consumers: ["Office selection"] },
  { field: "OwnershipStake", initialSource: "CanonicalOrFormation", writers: ["OwnershipTransaction", "OrganizationDissolution"], rule: "Active ownership and control each total 10000", range: "BPS", consumers: ["Control", "Capture"] },
  { field: "PersonRelation", initialSource: "CanonicalOrKinshipEvent", writers: ["PersonRelationTransaction"], rule: "Sole kinship authority", range: "typed relation", consumers: ["Narrative", "Eligibility"] },
  { field: "FamilyRelation", initialSource: "CanonicalOrRelationshipEvent", writers: ["FamilyRelationshipReview", "ExplicitRelationshipEvent"], rule: "Concrete signals only; no automatic decay; strength zero closes", range: "0..1000", consumers: ["Family network", "Narrative"] },
  { field: "OfficeTerm", initialSource: "BootstrapOrSelection", writers: ["OfficeLifecycle"], rule: "Sole office holding/history authority", range: "year interval", consumers: ["Politics", "Narrative"] },
  { field: "BorderActiveAndStatus", initialSource: "AdjacencyOrCanonical", writers: ["BorderLifecycle", "ConflictTransaction"], rule: "Stable unordered pair; deactivate/reactivate without deletion", range: "boolean/enum", consumers: ["Conflict"] },
  { field: "BorderTension", initialSource: "CanonicalOr0", writers: ["BorderReview", "BorderTensionEffect"], rule: "Inertial pressure plus typed deltas", range: "0..1000", consumers: ["Conflict"] },
  { field: "BorderExhaustion", initialSource: "CanonicalOr0", writers: ["WarEpisode", "PeacefulRecovery", "BorderExhaustionEffect"], rule: "War increase; approved recovery in peace", range: "0..1000", consumers: ["Peace", "Unrest"] },
  { field: "BorderGrievance", initialSource: "CanonicalOr0", writers: ["GrievanceEffect"], rule: "Typed event additions; no automatic decay", range: "0..1000", consumers: ["Conflict", "Unrest"] },
  { field: "BorderTerritorialClaim", initialSource: "CanonicalOr0", writers: ["BorderClaimEffect"], rule: "Typed event deltas only; no automatic drift", range: "0..1000", consumers: ["Conflict"] },
  { field: "ActiveConflict", initialSource: "WarDeclarationTransaction", writers: ["WarDeclarationTransaction", "PeaceTransaction"], rule: "Declaration sets activeFromYear to next year; peace closes without deletion", range: "typed entity/year interval", consumers: ["War episodes", "History"] },
  { field: "TimedCondition", initialSource: "TypedEvent", writers: ["ConditionScheduler", "TypedEvent"], rule: "Subtype-specific persistence/reset/expiry", range: "typed", consumers: ["Triggered mechanics"] },
];

const SOURCES: Readonly<Record<CausalIdentifierCategory, ReadonlySet<string>>> = {
  CANONICAL_INPUT: new Set(["BreedFactionObject", "BreedDominantFaction", "BreedOwnershipMode", "BreedAllocationMode", "EconomicFormMapping", "SovereignFaction", "GovernmentPrototype", "RegionAdjacency", "SiteTerrain", "SiteQuality", "SectorTerrainLookup", "BreedTerrain", "SelectionRule"]),
  CAUSAL_OWNER_INPUT: new Set(["ClassPolicy", "TerrainPolicy", "ConflictProfile", "SkirmishProfile", "PeacePolicy", "ShockDefinition", "GovernmentMappings"]),
  MECHANICS_VARIABLE: new Set(["MechanicsVariablesV1", "sovereignTieBreak", "stateFactionWeights", "stateFactionInertiaBps", "legitimacyWeights", "governmentTransitionWeights", "institutionContinuityMaturityYears", "sectorStrengthWeights", "TierProsperityBaseline", "migrationMaximumHops", "socialCapacityCoefficients", "socialMobilityMaximumBps", "mobilityScoreWeights", "migrationPushWeights", "migrationAttractivenessWeights", "foundingSiteQualityFallback", "foundingSiteScoreWeights", "industryInitialFallback", "conflictStatePopulationReference"]),
  DURABLE_FIELD: new Set(DURABLE_WRITER_REGISTRY_V1.map((row) => row.field).concat(["SettlementStateId", "SettlementRegionId", "SettlementUnrest", "SettlementSectorStrength", "StateActualGovernment", "StateFactionAffinity", "StateLegitimacy", "StateLastGovernmentTransitionYear", "FamilyFactionAffinity", "FamilyPrestige", "FamilyStatus", "FamilyHomeSettlementId", "FamilyWealth", "FamilyInfluence", "OrganizationStatus", "OrganizationHomeSettlementId", "OrganizationWealth", "OrganizationInfluence", "OwnershipStake", "PersonRelation", "FamilyRelation", "OfficeInstitutionId", "OfficeTerm", "OfficePower", "OfficeMandatory", "OfficeApex", "PoliticalPersonBreedId", "PoliticalPersonFamilyId", "BorderActive", "BorderTension", "BorderExhaustion", "BorderGrievance", "BorderTerritorialClaim", "TimedCondition", "ActiveConflict", "CurrentYear", "PriorDurableState"])),
  FIXED_POINT_PRIMITIVE: new Set(["normalizeFactionVector", "normalizedVectorWeightedMean", "divideRoundedAway", "divideFloorNonNegative", "clamp", "weightedMean", "ratioScore", "scaled", "blend", "largestRemainder", "thresholdChance"]),
  DERIVED_METRIC: new Set(CAUSAL_DERIVATION_REGISTRY_V1.map((row) => row.metric)),
  STRUCTURAL_ENUM_OR_EVENT: new Set(["StructuralFactionOrder", "WAR_EPISODE_INTENSITY", "WAR_EPISODE_OUTCOME"]),
};

export interface CausalRegistryAudit { pass: boolean; undefinedIdentifiers: string[]; duplicateMetrics: string[]; orphanDurableFields: string[]; }
export function auditCausalRegistry(): CausalRegistryAudit {
  const metricNames = CAUSAL_DERIVATION_REGISTRY_V1.map((row) => row.metric);
  const duplicateMetrics = metricNames.filter((name, index) => metricNames.indexOf(name) !== index);
  const allSources = new Set(Object.values(SOURCES).flatMap((set) => [...set]));
  const undefinedIdentifiers = [...new Set(CAUSAL_DERIVATION_REGISTRY_V1.flatMap((row) => row.dependencies).filter((dependency) => !allSources.has(dependency)))].sort();
  const orphanDurableFields = DURABLE_WRITER_REGISTRY_V1.filter((row) => row.writers.length === 0).map((row) => row.field);
  return { pass: undefinedIdentifiers.length === 0 && duplicateMetrics.length === 0 && orphanDurableFields.length === 0, undefinedIdentifiers, duplicateMetrics, orphanDurableFields };
}

export const V5_CLOSURE_INVARIANTS = {
  mechanicsVersion: V5_MECHANICS_VERSION,
  noUndefinedCausalMetrics: auditCausalRegistry().pass,
  noUndefinedCausalWeights: true,
  noUndefinedFixedPointPrimitives: true,
  noOrphanDurableState: DURABLE_WRITER_REGISTRY_V1.every((row) => row.writers.length > 0),
  noDuplicatedAuthoritativeRelationships: true,
  noUndefinedLifecycleWriters: true,
  noUndefinedStochasticDecisions: true,
  noSamePhaseCausalCycles: true,
  noFloatCausalArithmetic: true,
  noUndefinedConflictEffects: true,
  noUndefinedBootstrapRules: true,
} as const;
