import { describe, expect, it } from "vitest";
import { createAtrocityOccurrenceSlotsV5, validateAtrocityOccurrenceSlotsV5 } from "../../src/core/v5/atrocity-slots.js";
import { executeAtrocityOccurrenceV5, type AtrocityShockDefinitionV5 } from "../../src/core/v5/atrocities.js";
import { DEFAULT_DIAGNOSTIC_CONFIG_V1, DEFAULT_MECHANICS_VARIABLES_V1, DEFAULT_OPERATIONAL_CONFIG_V1, V5_CAUSAL_DERIVATION_VERSION, V5_MECHANICS_VERSION, V5_READ_MODEL_VERSION, V5_SCHEDULER_VERSION, diagnosticCandidateOwnerInputsV1, type CanonicalDataV5 } from "../../src/core/v5/config.js";
import { executeHistoricalConflictActionV5, type HistoricalConflictActionV5 } from "../../src/core/v5/conflict-actions.js";
import { acceptDerogatoryDecisionResponseV5, applyAcceptedDerogatoryDecisionBatchV5, buildDerogatoryDecisionBatchV5, renderExternalDerogatoryDecisionPromptV5, V5_EMPTY_DEROGATORY_DECISION_STREAM_HASH } from "../../src/core/v5/derogatory-decisions.js";
import { admitTargetedPopulationToEnclaveV5, foundEnclaveV5, integrateEnclaveV5 } from "../../src/core/v5/enclaves.js";
import { assertNoSecretEnclaveLeakV54, buildPrivateHistoricalExportV54, buildPublicHistoricalExportV54 } from "../../src/core/v5/historical-export.js";
import { establishResourceGeographyV5, updateIndustriesAndGuildsV5 } from "../../src/core/v5/historical-dynamism.js";
import { CANDIDATE_DEROGATORY_MEMBERSHIP_SLICING_POLICY_V1, CANDIDATE_HISTORICAL_DYNAMISM_POLICIES_V1, CANDIDATE_RESOURCE_INDUSTRY_POLICY_V1, PolicyAuthorityRequiredV5, historicalPolicyHashV5, type DerogatoryMembershipSlicingPolicyV1 } from "../../src/core/v5/historical-policies.js";
import { projectWorldStateV54ReadOnly, restoreWorldStateV5 } from "../../src/core/v5/persistence.js";
import { adjustTargetedFactionOpinionV5, applyTargetedGrowthSuppressionV5, applyTargetedMortalityV5, causalPopulationTotalsV5, ensurePopulationSlicesV5, materializeDerogatoryMembershipV5, transferTargetedPopulationV5, validatePopulationPartitionV5 } from "../../src/core/v5/population-slices.js";
import { V5_ATROCITY_OCCURRENCE_IDS, V5_CIVIC_INSTITUTION_TYPES, V5_DEROGATORY_GROUP_IDS, V5_DEROGATORY_TARGETING_SCOPES, V5_INDUSTRY_TYPES, V5_RESOURCE_TYPES, V5_SECURITY_FORCE_TYPES, type WorldKey, type WorldStateV5 } from "../../src/core/v5/types.js";
import { continueV5History } from "../../src/core/v5/runner.js";
import { normalizeSeed } from "../../src/core/v5/random.js";
import { reconcileChamberAuthorityV5 } from "../../src/core/v5/chambers.js";
import { fillMandatoryOfficeVacancies } from "../../src/core/v5/politics.js";

const government = { governmentFormId: "GOV", doctrineVector: { CONCORD: 1000, SCHISM: 0, RUIN: 0 }, administrationMode: "CIVIC", legitimacyBasis: "CIVIC", authoritySource: "CIVIC", franchiseBreadth: 500, requiredInstitutions: [] };
const canonical: CanonicalDataV5 = {
  schemaVersion: "echoes-canonical-data-v5", canonicalBundleHash: "v54-fixture",
  breeds: [
    { breedId: "HUMAN", populationKind: "HUMAN", groupId: "H", factionObject: { CONCORD: 8, SCHISM: 1, RUIN: 1 }, dominantFaction: ["CONCORD"], terrainBroad: ["FOREST"], terrainSpecific: ["CAVERN", "WOODLAND"], ownershipMode: "COMMON", allocationMode: "MARKET" },
    { breedId: "BEAST", populationKind: "BEAST", groupId: "B", factionObject: { CONCORD: 1, SCHISM: 8, RUIN: 1 }, dominantFaction: ["SCHISM"], terrainBroad: ["GRASSLAND"], terrainSpecific: ["STEPPE"], ownershipMode: "COMMON", allocationMode: "MARKET" },
  ],
  sites: [
    { siteId: "SITE_1", regionId: "R1", regionName: "One", latitude: 0, longitude: 0, terrainBroad: ["FOREST", "MOUNTAIN"], terrainSpecific: ["CAVERN", "WOODLAND"], quality: 800 },
    { siteId: "SITE_2", regionId: "R2", regionName: "Two", latitude: 1, longitude: 1, terrainBroad: ["GRASSLAND"], terrainSpecific: ["STEPPE"], quality: 600 },
  ],
  regions: [{ regionId: "R1", directedAdjacentRegionIds: ["R2"] }, { regionId: "R2", directedAdjacentRegionIds: ["R1"] }], governments: [government],
  economicForms: [{ ownershipMode: "COMMON", allocationMode: "MARKET", economicForm: "MARKET" }], physicalPois: [], routeCorridors: [],
  sovereigns: { CONCORD: { sovereignFaction: "CONCORD", breedId: "HUMAN", seizureTargetSiteId: "SITE_1" }, SCHISM: { sovereignFaction: "SCHISM", breedId: "BEAST", seizureTargetSiteId: "SITE_2" }, RUIN: { sovereignFaction: "RUIN", breedId: "HUMAN", seizureTargetSiteId: "SITE_1" } },
  groupRegionAssignments: { CONCORD: { H: "R1", B: "R2" }, SCHISM: { H: "R1", B: "R2" }, RUIN: { H: "R1", B: "R2" } }, initialSettlements: [], canonicalLabels: {}, canonicalEvents: [],
};

const baseState = (worldKey: WorldKey = "CONCORD", year = 10): WorldStateV5 => ensurePopulationSlicesV5({
  schemaVersion: "echoes-world-state-v5", worldKey, year,
  cohorts: [
    { settlementId: "S1", breedId: "HUMAN", tiers: { HIGH: { population: 1000n, prosperity: 700 }, MID: { population: 1000n, prosperity: 500 }, LOW: { population: 1000n, prosperity: 300 } } },
    { settlementId: "S2", breedId: "BEAST", tiers: { HIGH: { population: 500n, prosperity: 600 }, MID: { population: 500n, prosperity: 500 }, LOW: { population: 500n, prosperity: 400 } } },
  ],
  settlements: [
    { settlementId: "S1", siteId: "SITE_1", regionId: "R1", stateId: "STATE_A", foundedYear: 0, unrest: 0, sectorStrengths: { LAND_AND_FOOD: 700, EXTRACTION: 700, MANUFACTURE: 700, TRADE_AND_TRANSPORT: 700, KNOWLEDGE_AND_SERVICES: 700 } },
    { settlementId: "S2", siteId: "SITE_2", regionId: "R2", stateId: "STATE_B", foundedYear: 0, unrest: 100, sectorStrengths: { LAND_AND_FOOD: 500, EXTRACTION: 500, MANUFACTURE: 500, TRADE_AND_TRANSPORT: 500, KNOWLEDGE_AND_SERVICES: 500 } },
  ],
  states: [
    { stateId: "STATE_A", actualGovernment: "GOV", factionAffinity: { CONCORD: 800, SCHISM: 100, RUIN: 100 }, dominantFaction: "CONCORD", legitimacy: 800, qualifyingGovernmentReviewCount: 0, lastGovernmentTransitionYear: 0, routineTransitionCooldownUntilYear: 0 },
    { stateId: "STATE_B", actualGovernment: "GOV", factionAffinity: { CONCORD: 100, SCHISM: 800, RUIN: 100 }, dominantFaction: "SCHISM", legitimacy: 500, qualifyingGovernmentReviewCount: 0, lastGovernmentTransitionYear: 0, routineTransitionCooldownUntilYear: 0 },
  ],
  families: [], politicalPeople: [], personRelations: [], organizations: [], institutions: [{ institutionId: "CIVIC_S1", stateId: "STATE_A", institutionType: "BUREAUCRACY", jurisdictionSettlementId: "S1", capacity: 1000, foundedYear: 0, dissolvedYear: null }], offices: [], officeTerms: [], ownershipStakes: [], familyRelations: [], borderRelations: [{ borderRelationId: "BORDER_AB", stateAId: "STATE_A", stateBId: "STATE_B", activeBorder: true, tension: 500, exhaustion: 0, grievance: 0, territorialClaim: 500, status: "PEACE", warDeclaredYear: null, warEndedYear: null, cooldownUntilYear: null }], timedConditions: [], activeConflicts: [], worldRoutes: [], resourceNodes: [], worldResourceStates: [], industries: [], securityForces: [], diplomaticRelations: [], diplomaticAgreements: [], conflictEpisodes: [], settlementControlTerms: [], derogatoryTargetSelections: [], localAtrocityResponses: [], forcedDisplacements: [], enclaves: [],
}, canonical);

const slicingPolicy = (withOverlap = false): DerogatoryMembershipSlicingPolicyV1 => ({ ...CANDIDATE_DEROGATORY_MEMBERSHIP_SLICING_POLICY_V1, predicates: CANDIDATE_DEROGATORY_MEMBERSHIP_SLICING_POLICY_V1.predicates.map((row) => row.groupId === "homosexual" ? { ...row, status: "READY" as const, aggregateShareBps: 2500, authorityRef: "TEST_SHARE_25" } : row.groupId === "bisexual" ? { ...row, status: "READY" as const, aggregateShareBps: 5000, authorityRef: "TEST_SHARE_50" } : row), conditionalOverlapSharesBps: withOverlap ? { "bisexual&homosexual": 2000 } : {} });
const owner = diagnosticCandidateOwnerInputsV1({ GOV: {} });

describe("V5.4 structural contracts", () => {
  it("retains the V5.4 causal version contracts during the Organization-integrity correction", () => { expect(V5_SCHEDULER_VERSION).toBe("echoes-scheduler-v5.4.0"); expect(V5_MECHANICS_VERSION).toBe("echoes-mechanics-v5.4.0"); expect(V5_READ_MODEL_VERSION).toBe("echoes-read-model-v1.2.0"); expect(V5_CAUSAL_DERIVATION_VERSION).toBe("echoes-derived-metrics-v1.1.0"); });
  it("registers the required resource, industry, civic, security, Group, and 21-scope enums", () => { expect(V5_RESOURCE_TYPES).toHaveLength(24); expect(V5_INDUSTRY_TYPES).toHaveLength(40); expect(V5_CIVIC_INSTITUTION_TYPES).toHaveLength(12); expect(V5_SECURITY_FORCE_TYPES).toHaveLength(7); expect(V5_DEROGATORY_GROUP_IDS).toHaveLength(28); expect(V5_DEROGATORY_TARGETING_SCOPES).toHaveLength(21); });
  it("creates exactly 18 Witness slots in canonical order and no Witness 18", () => { const slots = createAtrocityOccurrenceSlotsV5(); validateAtrocityOccurrenceSlotsV5(slots); expect(slots.map((row) => row.occurrenceId)).toEqual(V5_ATROCITY_OCCURRENCE_IDS); expect(slots.some((row) => row.occurrenceId.includes("18"))).toBe(false); expect(slots.every((row) => row.status === "NOT_CONFIGURED")).toBe(true); });
  it("projects missing V5.4 fields read-only without changing restored legacy state", () => { const raw = structuredClone(baseState()) as WorldStateV5; delete raw.populationSlices; delete raw.enclaves; const restored = restoreWorldStateV5(JSON.parse(JSON.stringify(raw, (_key, value) => typeof value === "bigint" ? value.toString() : value))); expect(restored.populationSlices).toBeUndefined(); const projected = projectWorldStateV54ReadOnly(restored); expect(projected.populationSlices).toEqual([]); expect(restored.populationSlices).toBeUndefined(); });
  it("blocks an unapproved candidate only when its causal operation is reached and discloses the whole policy", () => { const canonicalOwner = { ...owner, diagnosticHistoricalPolicyOptIns: [] }; try { establishResourceGeographyV5({ ...baseState(), year: 1 }, { canonical, ownerInputs: canonicalOwner, mode: "CANONICAL" }); throw new Error("expected blocker"); } catch (error) { expect(error).toBeInstanceOf(PolicyAuthorityRequiredV5); const blocker = (error as PolicyAuthorityRequiredV5).blocker; expect(blocker).toMatchObject({ policyKey: "RESOURCE_INDUSTRY", causalOperation: "PLACE_PHYSICAL_RESOURCE_GEOGRAPHY", worldKey: "CONCORD", year: 1 }); expect(blocker.policyDocument).toEqual(CANDIDATE_HISTORICAL_DYNAMISM_POLICIES_V1.RESOURCE_INDUSTRY); expect(blocker.humanReadablePolicy).toContain("resource geography"); } });
  it("rolls back the whole unpersisted year and checkpoints the prior state at a point-of-use blocker", () => { const initialStates = { CONCORD: baseState("CONCORD", 0), SCHISM: baseState("SCHISM", 0), RUIN: baseState("RUIN", 0) }; const paused: number[] = []; const result = continueV5History({ canonical, ownerInputs: { ...owner, diagnosticHistoricalPolicyOptIns: [] }, mechanics: DEFAULT_MECHANICS_VARIABLES_V1, operational: DEFAULT_OPERATIONAL_CONFIG_V1, diagnostic: DEFAULT_DIAGNOSTIC_CONFIG_V1, normalizedSeed: normalizeSeed("POLICY_ATOMICITY"), mode: "CANONICAL", throughYear: 1, initialStates, retainHistory: true, onPauseCheckpoint: (states) => paused.push(states.CONCORD.year) }); expect(result).toMatchObject({ status: "WAITING_FOR_POLICY_AUTHORITY", completedYear: 0 }); expect(Object.values(result.states).every((state) => state.year === 0 && state.resourceNodes?.length === 0)).toBe(true); expect(result.events.CONCORD).toEqual([]); expect(paused).toEqual([0]); });
  it("allows individual diagnostic policy opt-in and separates physical identity from world control", () => { const resourcePolicy = { ...CANDIDATE_RESOURCE_INDUSTRY_POLICY_V1, placementRules: CANDIDATE_RESOURCE_INDUSTRY_POLICY_V1.placementRules.map((row) => ({ ...row, scarcityDivisor: 1 })) }; const inputOwner = { ...owner, historicalDynamismPolicies: { ...CANDIDATE_HISTORICAL_DYNAMISM_POLICIES_V1, RESOURCE_INDUSTRY: resourcePolicy }, diagnosticHistoricalPolicyOptIns: ["RESOURCE_INDUSTRY" as const] }; const concord = establishResourceGeographyV5({ ...baseState("CONCORD"), year: 1 }, { canonical, ownerInputs: inputOwner, mode: "DIAGNOSTIC" }).state; const ruin = establishResourceGeographyV5({ ...baseState("RUIN"), year: 1 }, { canonical, ownerInputs: inputOwner, mode: "DIAGNOSTIC" }).state; expect(concord.resourceNodes!.length).toBeGreaterThan(0); expect(concord.resourceNodes!.map((row) => row.resourceNodeId)).toEqual(ruin.resourceNodes!.map((row) => row.resourceNodeId)); expect(concord.worldResourceStates!.every((row) => row.worldResourceStateId.includes("CONCORD"))).toBe(true); });
});

describe("V5.4 exact population partitions", () => {
  it("materializes a fractional cross-cutting predicate with exact integer totals", () => { const state = materializeDerogatoryMembershipV5(baseState(), canonical, slicingPolicy(), "homosexual"); validatePopulationPartitionV5(state); expect(state.populationSlices!.filter((row) => row.membershipSignature.includes("homosexual")).reduce((sum, row) => sum + row.population, 0n)).toBe(1125n); });
  it("blocks unresolved overlaps instead of assuming independence", () => { const first = materializeDerogatoryMembershipV5(baseState(), canonical, slicingPolicy(), "homosexual"); expect(() => materializeDerogatoryMembershipV5(first, canonical, slicingPolicy(), "bisexual")).toThrow(/conditional overlap share/); });
  it("splits overlapping predicates with approved conditional shares and preserves equality", () => { let state = materializeDerogatoryMembershipV5(baseState(), canonical, slicingPolicy(true), "homosexual"); state = materializeDerogatoryMembershipV5(state, canonical, slicingPolicy(true), "bisexual"); validatePopulationPartitionV5(state); expect(state.populationSlices!.some((row) => row.membershipSignature.join("&") === "bisexual&homosexual")).toBe(true); });
  it("changes opinion only on the selected slice", () => { const state = materializeDerogatoryMembershipV5(baseState(), canonical, slicingPolicy(), "homosexual"); const changed = adjustTargetedFactionOpinionV5(state, "homosexual", "RUIN", 200, "OPINION"); expect(changed.populationSlices!.filter((row) => row.membershipSignature.includes("homosexual")).every((row) => row.factionOpinion.RUIN > state.populationSlices!.find((prior) => prior.populationSliceId === row.populationSliceId)!.factionOpinion.RUIN)).toBe(true); expect(changed.populationSlices!.filter((row) => !row.membershipSignature.includes("homosexual")).every((row) => row.factionOpinion.RUIN === state.populationSlices!.find((prior) => prior.populationSliceId === row.populationSliceId)!.factionOpinion.RUIN)).toBe(true); });
  it("apportions mortality across the fractional target only", () => { const state = materializeDerogatoryMembershipV5(baseState(), canonical, slicingPolicy(), "homosexual"); const applied = applyTargetedMortalityV5(state, "homosexual", 1000, "MORTALITY"); expect(applied.deaths).toBe(112n); expect(causalPopulationTotalsV5(applied.state).causalTotalPopulation).toBe(4388n); validatePopulationPartitionV5(applied.state); });
  it("stores growth suppression only on exact target slices", () => { const state = materializeDerogatoryMembershipV5(baseState(), canonical, slicingPolicy(), "homosexual"); const changed = applyTargetedGrowthSuppressionV5(state, "homosexual", -500_000, 25, "SUPPRESS"); expect(changed.populationSlices!.filter((row) => row.membershipSignature.includes("homosexual")).every((row) => row.growthModifierPpm === -500_000)).toBe(true); expect(changed.populationSlices!.filter((row) => !row.membershipSignature.includes("homosexual")).every((row) => row.growthModifierPpm === 0)).toBe(true); });
  it("preserves signature and opinion during a forced public transfer", () => { const state = materializeDerogatoryMembershipV5(baseState(), canonical, CANDIDATE_DEROGATORY_MEMBERSHIP_SLICING_POLICY_V1, "humans"); const moved = transferTargetedPopulationV5({ state, groupId: "humans", sourceLocationType: "PUBLIC_SETTLEMENT", sourceLocationId: "S1", destinationLocationType: "PUBLIC_SETTLEMENT", destinationLocationId: "S2", shareBps: 1000, sourceEventId: "FORCED" }); expect(moved.transferred).toBe(300n); expect(moved.state.populationSlices!.filter((row) => row.locationId === "S2" && row.breedId === "HUMAN").every((row) => row.membershipSignature.includes("humans") && row.factionOpinion.CONCORD === 800)).toBe(true); validatePopulationPartitionV5(moved.state); });
});

describe("V5.4 Derogatory external decisions", () => {
  const statesAt = (year: number): Record<WorldKey, WorldStateV5> => ({
    CONCORD: { ...baseState("CONCORD", year), derogatoryTargetSelections: [] },
    SCHISM: { ...baseState("SCHISM", year), derogatoryTargetSelections: [] },
    RUIN: { ...baseState("RUIN", year), derogatoryTargetSelections: [] },
  });
  it("builds one immutable 63-decision year-15 SELECT batch", () => { const batch = buildDerogatoryDecisionBatchV5(statesAt(14), 15, CANDIDATE_DEROGATORY_MEMBERSHIP_SLICING_POLICY_V1); expect(batch.requests).toHaveLength(63); expect(batch.requests.every((row) => row.allowedActions.join() === "SELECT" && row.priorGroupId === null)).toBe(true); expect(batch.batchId).toContain(batch.reviewYear.toString()); });
  it("renders a complete external prompt without mutating immutable batch identity", () => { const batch = buildDerogatoryDecisionBatchV5(statesAt(14), 15, CANDIDATE_DEROGATORY_MEMBERSHIP_SLICING_POLICY_V1); const prompt = renderExternalDerogatoryDecisionPromptV5(batch); expect(prompt.length).toBeGreaterThan(batch.promptText.length); expect(prompt).toContain("IMMUTABLE BATCH CONTEXT"); expect(prompt).toContain("REQUIRED RESPONSE TEMPLATE"); expect(prompt).toContain('"schemaVersion": "echoes-derogatory-decision-response-v1"'); expect(prompt).toContain(batch.requests[0]!.decisionId); expect(prompt).toContain(batch.requests.at(-1)!.decisionId); expect(prompt).toContain('"publicPopulationBeforeReview"'); expect(prompt).toContain('"readyGroupIds"'); expect(buildDerogatoryDecisionBatchV5(statesAt(14), 15, CANDIDATE_DEROGATORY_MEMBERSHIP_SLICING_POLICY_V1)).toEqual(batch); });
  it("rejects partial coverage and invalid year-15 KEEP", () => { const batch = buildDerogatoryDecisionBatchV5(statesAt(14), 15, CANDIDATE_DEROGATORY_MEMBERSHIP_SLICING_POLICY_V1); const response = { schemaVersion: "echoes-derogatory-decision-response-v1" as const, batchId: batch.batchId, contextSha256: batch.contextSha256, promptSha256: batch.promptSha256, provider: "fixture", model: "fixture", authorityRef: "TEST_FIXTURE", decisions: batch.requests.slice(0, 62).map((row) => ({ decisionId: row.decisionId, action: "KEEP" as const, selectedGroupId: "humans" as const })) }; expect(() => acceptDerogatoryDecisionResponseV5(batch, response)).toThrow(/63/); });
  it("accepts SELECT then enforces KEEP-preserves and REPLACE-differs", () => { const firstBatch = buildDerogatoryDecisionBatchV5(statesAt(14), 15, CANDIDATE_DEROGATORY_MEMBERSHIP_SLICING_POLICY_V1); const firstResponse = { schemaVersion: "echoes-derogatory-decision-response-v1" as const, batchId: firstBatch.batchId, contextSha256: firstBatch.contextSha256, promptSha256: firstBatch.promptSha256, provider: "fixture", model: "fixture", authorityRef: "TEST_FIXTURE", decisions: firstBatch.requests.map((row) => ({ decisionId: row.decisionId, action: "SELECT" as const, selectedGroupId: "humans" as const })) }; const first = acceptDerogatoryDecisionResponseV5(firstBatch, firstResponse); const laterStates = applyAcceptedDerogatoryDecisionBatchV5(statesAt(14), canonical, CANDIDATE_DEROGATORY_MEMBERSHIP_SLICING_POLICY_V1, first); for (const world of ["CONCORD", "SCHISM", "RUIN"] as const) laterStates[world].year = 149; const laterBatch = buildDerogatoryDecisionBatchV5(laterStates, 150, CANDIDATE_DEROGATORY_MEMBERSHIP_SLICING_POLICY_V1); const keepResponse = { ...firstResponse, batchId: laterBatch.batchId, contextSha256: laterBatch.contextSha256, promptSha256: laterBatch.promptSha256, decisions: laterBatch.requests.map((row) => ({ decisionId: row.decisionId, action: "KEEP" as const, selectedGroupId: "humans" as const })) }; expect(acceptDerogatoryDecisionResponseV5(laterBatch, keepResponse, first.decisionStreamHash).acceptedSelections).toHaveLength(63); const invalid = { ...keepResponse, decisions: keepResponse.decisions.map((row, index) => index === 0 ? { ...row, action: "REPLACE" as const } : row) }; expect(() => acceptDerogatoryDecisionResponseV5(laterBatch, invalid, first.decisionStreamHash)).toThrow(/different group/); });
});

describe("V5.4 Enclaves, atrocities, industry, and conflict", () => {
  function refugeReady(year = 20): WorldStateV5 { let state = materializeDerogatoryMembershipV5(baseState("CONCORD", year), canonical, CANDIDATE_DEROGATORY_MEMBERSHIP_SLICING_POLICY_V1, "humans"); state.derogatoryTargetSelections = [{ selectionId: "SEL", worldKey: "CONCORD", scope: V5_DEROGATORY_TARGETING_SCOPES[0], reviewYear: 15, action: "SELECT", priorGroupId: null, selectedGroupId: "humans", effectiveFromYear: 15, effectiveUntilYear: null, decisionBatchId: "BATCH", responseSha256: "a".repeat(64), provenanceRef: "TEST" }]; state.localAtrocityResponses = [{ responseId: "SANCTUARY", occurrenceId: "ATROCITY_WITNESS_17", settlementId: "S1", stateId: "STATE_A", targetGroupId: "humans", responseType: "SANCTUARY", intensity: 800, sourceEventId: "PERSECUTION" }]; return state; }
  it("admits and integrates exact Enclave slices without duplication", () => { const state = refugeReady(); const policy = CANDIDATE_HISTORICAL_DYNAMISM_POLICIES_V1.PERSECUTION_DISPLACEMENT_ENCLAVE; const founded = foundEnclaveV5({ state, canonical, policy, hostSettlementId: "S1", targetGroupId: "humans", form: "CAVERN", secrecyState: "HIDDEN", sourceEventId: "PERSECUTION", authorization: { targetingSelectionId: "SEL", persecutionOrDisplacementEventId: "PERSECUTION", sanctuaryResponseId: "SANCTUARY", authorizationRef: "TEST_AUTH" } }); const admitted = admitTargetedPopulationToEnclaveV5({ state: founded.state, policy, enclaveId: founded.enclave.enclaveId, sourceSettlementId: "S1", groupId: "humans", shareBps: 1000, sourceEventId: "PERSECUTION", cause: "PERSECUTION" }); expect(causalPopulationTotalsV5(admitted.state)).toEqual({ publicPopulation: 4200n, enclavePopulation: 300n, causalTotalPopulation: 4500n }); expect(admitted.state.enclaves![0]!.supportBurden).toBeGreaterThan(0); const integrated = integrateEnclaveV5(admitted.state, founded.enclave.enclaveId, "INTEGRATE"); expect(causalPopulationTotalsV5(integrated)).toEqual({ publicPopulation: 4500n, enclavePopulation: 0n, causalTotalPopulation: 4500n }); validatePopulationPartitionV5(integrated); });
  it("redacts HIDDEN and anonymizes RUMORED Enclaves before public serialization", () => { const state = refugeReady(); const founded = foundEnclaveV5({ state, canonical, policy: CANDIDATE_HISTORICAL_DYNAMISM_POLICIES_V1.PERSECUTION_DISPLACEMENT_ENCLAVE, hostSettlementId: "S1", targetGroupId: "humans", form: "CAVERN", secrecyState: "HIDDEN", sourceEventId: "PERSECUTION", authorization: { targetingSelectionId: "SEL", persecutionOrDisplacementEventId: "PERSECUTION", sanctuaryResponseId: "SANCTUARY", authorizationRef: "TEST_AUTH" } }); const publicExport = buildPublicHistoricalExportV54(founded.state, []); expect(publicExport.enclaves).toEqual([]); expect(buildPrivateHistoricalExportV54(founded.state, []).enclaves).toHaveLength(1); expect(() => assertNoSecretEnclaveLeakV54(founded.state, publicExport)).not.toThrow(); const rumored = { ...founded.state, enclaves: founded.state.enclaves!.map((row) => ({ ...row, secrecyState: "RUMORED" as const })) }; expect(buildPublicHistoricalExportV54(rumored, []).enclaves).toEqual([{ enclaveId: null, hostSettlementId: "S1", secrecyState: "RUMORED" }]); });
  it("prevents a disabled atrocity slot from executing", () => { const definition: AtrocityShockDefinitionV5 = { schemaVersion: "echoes-atrocity-shock-definition-v1", shockDefinitionId: "SHOCK", occurrenceId: "ATROCITY_WITNESS_17", triggerYear: 20, targetScope: V5_DEROGATORY_TARGETING_SCOPES[0], authorityStatus: "TEST_FIXTURE", authorityRef: "TEST", effects: [] }; expect(() => executeAtrocityOccurrenceV5({ state: refugeReady(), canonical, ownerInputs: owner, mode: "DIAGNOSTIC", definition })).toThrow(/NOT_CONFIGURED/); });
  it("resolves a configured atrocity against exact slices with mortality, displacement, confiscation, suppression, opinion, response, and Enclave accounting", () => { const slots = createAtrocityOccurrenceSlotsV5().map((row) => row.occurrenceId === "ATROCITY_WITNESS_17" ? { ...row, status: "CONFIGURED" as const, triggerYear: 20, targetScope: V5_DEROGATORY_TARGETING_SCOPES[0], shockDefinitionId: "SHOCK" } : row); const fixtureOwner = { ...owner, atrocityOccurrenceSlots: slots }; const definition: AtrocityShockDefinitionV5 = { schemaVersion: "echoes-atrocity-shock-definition-v1", shockDefinitionId: "SHOCK", occurrenceId: "ATROCITY_WITNESS_17", triggerYear: 20, targetScope: V5_DEROGATORY_TARGETING_SCOPES[0], authorityStatus: "TEST_FIXTURE", authorityRef: "TEST", effects: [{ type: "MORTALITY", mortalityBps: 1000 }, { type: "GROWTH_SUPPRESSION", modifierPpm: -500_000, durationYears: 10 }, { type: "SEIZURE", confiscationScore: 600 }, { type: "RESTRICTION", restrictionKey: "MOVEMENT" }, { type: "FACTION_OPINION", faction: "RUIN", delta: -100 }, { type: "SANCTUARY", hostSettlementId: "S1" }, { type: "ENCLAVE_AUTHORIZATION", hostSettlementId: "S1", form: "CAVERN", secrecyState: "HIDDEN", authorizationRef: "TEST_AUTH" }, { type: "DISPLACEMENT", sourceSettlementId: "S1", shareBps: 1000, destination: "AUTHORIZED_ENCLAVE" }] }; const resolved = executeAtrocityOccurrenceV5({ state: refugeReady(), canonical, ownerInputs: fixtureOwner, mode: "DIAGNOSTIC", definition }); expect(resolved.event.payload).toMatchObject({ deaths: "300", displaced: "270", targetPopulationBefore: "3000" }); expect(causalPopulationTotalsV5(resolved.state)).toEqual({ publicPopulation: 3930n, enclavePopulation: 270n, causalTotalPopulation: 4200n }); expect(resolved.state.populationSlices!.filter((row) => row.membershipSignature.includes("humans")).every((row) => row.confiscationScore === 600 && row.growthModifierPpm === -500_000 && row.factionOpinion.RUIN === 0)).toBe(true); });
  it("represents all industries and forms Guilds only after the configured review count", () => { const resourcePolicy = { ...CANDIDATE_RESOURCE_INDUSTRY_POLICY_V1, guildRequiredReviews: 1, guildFormationThreshold: 400, placementRules: CANDIDATE_RESOURCE_INDUSTRY_POLICY_V1.placementRules.map((row) => ({ ...row, scarcityDivisor: 1 })) }; const fixtureOwner = { ...owner, historicalDynamismPolicies: { ...CANDIDATE_HISTORICAL_DYNAMISM_POLICIES_V1, RESOURCE_INDUSTRY: resourcePolicy } }; let state = establishResourceGeographyV5({ ...baseState(), year: 5 }, { canonical, ownerInputs: fixtureOwner, mode: "DIAGNOSTIC" }).state; const result = updateIndustriesAndGuildsV5(state, { canonical, ownerInputs: fixtureOwner, mode: "DIAGNOSTIC" }); state = result.state; expect(state.industries).toHaveLength(state.settlements.length * V5_INDUSTRY_TYPES.length); expect(state.organizations.some((row) => row.type === "GUILD")).toBe(true); expect(state.institutions.filter((row) => row.institutionType === "GUILD").every((row) => !state.offices.some((office) => office.institutionId === row.institutionId))).toBe(true); });
  it("keeps occupation separate from legal State membership until explicit conquest", () => { const occupation = executeHistoricalConflictActionV5({ state: { ...baseState(), year: 30 }, canonical, ownerInputs: owner, mode: "DIAGNOSTIC", action: { actionId: "OCCUPY", year: 30, type: "OCCUPATION_CAPTURE", settlementId: "S1", controllerStateId: "STATE_B" } }); const occupied = occupation.state; expect(occupied.settlements.find((row) => row.settlementId === "S1")!.stateId).toBe("STATE_A"); expect(occupied.settlementControlTerms!.at(-1)).toMatchObject({ controllerStateId: "STATE_B", legalStateId: "STATE_A", controlType: "OCCUPATION" }); expect(occupation.events.map((event) => event.eventType)).not.toContain("StateMembershipChanged"); const conquest = executeHistoricalConflictActionV5({ state: { ...occupied, year: 31 }, canonical, ownerInputs: owner, mode: "DIAGNOSTIC", action: { actionId: "CONQUER", year: 31, type: "CONQUEST", settlementId: "S1", controllerStateId: "STATE_B" } }); expect(conquest.state.settlements.find((row) => row.settlementId === "S1")!.stateId).toBe("STATE_B"); expect(conquest.events.map((event) => event.eventType)).toContain("StateMembershipChanged"); });
  it("reconciles Conclave authority across occupation, conquest, treaty membership, and a later term cycle", () => {
    const selectionRule = { selectionMethod: "RULER_APPOINTMENT" as const, scope: "STATE" as const, requiresTrackedLineage: false, eligibleTiers: ["HIGH" as const, "MID" as const], minimumFactionCompatibility: 0, stochasticTies: false, scoreWeights: { factionFit: 3500, classFit: 1000, localSupport: 3000, lineageFit: 1500, ruleSpecificFit: 1000 } };
    const chamberCanonical: CanonicalDataV5 = { ...canonical, governments: [{ ...government, requiredInstitutions: [{ institutionType: "GOVERNMENT", offices: [{ jurisdictionSettlementId: null, titleKey: "RULER", power: 1000, mandatory: true, apex: true, termYears: 2, selectionRule }] }] }] };
    let state = reconcileChamberAuthorityV5({ ...baseState(), year: 30 }, chamberCanonical).state;
    state = fillMandatoryOfficeVacancies(state, chamberCanonical, owner, DEFAULT_MECHANICS_VARIABLES_V1, normalizeSeed("CONQUEST_CHAMBER"), "INITIAL").state;
    const stateASeat = state.offices.find((office) => office.officeId.includes("STATE_A_S1"))!;
    expect(stateASeat.mandatory).toBe(true);
    const occupied = executeHistoricalConflictActionV5({ state: { ...state, year: 31 }, canonical: chamberCanonical, ownerInputs: owner, mode: "DIAGNOSTIC", action: { actionId: "OCCUPATION", year: 31, type: "OCCUPATION_CAPTURE", settlementId: "S1", controllerStateId: "STATE_B" } }).state;
    expect(reconcileChamberAuthorityV5(occupied, chamberCanonical).state.offices.find((office) => office.officeId === stateASeat.officeId)?.mandatory).toBe(true);
    const conquered = executeHistoricalConflictActionV5({ state: { ...occupied, year: 32 }, canonical: chamberCanonical, ownerInputs: owner, mode: "DIAGNOSTIC", action: { actionId: "CONQUEST", year: 32, type: "CONQUEST", settlementId: "S1", controllerStateId: "STATE_B" } }).state;
    const conquestReconciled = reconcileChamberAuthorityV5(conquered, chamberCanonical);
    expect(conquestReconciled.state.offices.find((office) => office.officeId === stateASeat.officeId)).toMatchObject({ mandatory: false });
    expect(conquestReconciled.events.map((event) => event.eventType)).toContain("ConclaveSeatRetired");
    state = fillMandatoryOfficeVacancies(conquestReconciled.state, chamberCanonical, owner, DEFAULT_MECHANICS_VARIABLES_V1, normalizeSeed("CONQUEST_CHAMBER"), "AFTER_CONQUEST").state;
    const stateBSeat = state.offices.find((office) => office.officeId.includes("STATE_B_S1"))!;
    expect(stateBSeat.mandatory).toBe(true);
    state = { ...state, year: 34, officeTerms: state.officeTerms.map((term) => term.officeId === stateBSeat.officeId ? { ...term, endYear: 34, terminationReason: "TERM_EXPIRED" as const } : term) };
    state = fillMandatoryOfficeVacancies(state, chamberCanonical, owner, DEFAULT_MECHANICS_VARIABLES_V1, normalizeSeed("CONQUEST_CHAMBER"), "NEXT_CYCLE").state;
    expect(state.officeTerms.some((term) => term.officeId === stateBSeat.officeId && term.startYear === 34)).toBe(true);
    const treaty = executeHistoricalConflictActionV5({ state: { ...state, year: 35 }, canonical: chamberCanonical, ownerInputs: owner, mode: "DIAGNOSTIC", action: { actionId: "TREATY_MEMBERSHIP", year: 35, type: "TREATY", stateAId: "STATE_A", stateBId: "STATE_B", settlementId: "S1", legalStateId: "STATE_A" } }).state;
    const treatyReconciled = reconcileChamberAuthorityV5(treaty, chamberCanonical);
    expect(() => fillMandatoryOfficeVacancies(treatyReconciled.state, chamberCanonical, owner, DEFAULT_MECHANICS_VARIABLES_V1, normalizeSeed("CONQUEST_CHAMBER"), "AFTER_TREATY")).not.toThrow();
    expect(treatyReconciled.state.offices.find((office) => office.officeId === stateASeat.officeId)).toMatchObject({ mandatory: true });
  });
  it("executes disputes, skirmishes, wars, embargoes, piracy, banditry, resource seizure, siege, and treaty as typed actions", () => { const fixture = { ...baseState(), year: 40, industries: [{ industryStateId: "IND", settlementId: "S1", industryType: "SHIPPING" as const, strength: 500, employment: 500, dependency: 500, coercion: 0, disruptedUntilYear: null, supportingResourceNodeIds: ["RESOURCE"], supportingInstitutionIds: [], sourcePolicyRef: "TEST" }], resourceNodes: [{ resourceNodeId: "RESOURCE", resourceType: "WOOD" as const, siteId: "SITE_1", regionId: "R1", quality: 500, capacityClass: "MODERATE" as const, renewable: true, accessDifficulty: 200, placementAuthorityRef: "TEST" }], worldResourceStates: [{ worldResourceStateId: "WORLD_RESOURCE", resourceNodeId: "RESOURCE", controllerType: "STATE" as const, controllerId: "STATE_A", discoveryYear: 1, availability: "AVAILABLE" as const, seizedByEventId: null }] }; const actions: HistoricalConflictActionV5[] = [{ actionId: "DISPUTE", year: 40, type: "BORDER_DISPUTE", borderRelationId: "BORDER_AB", attackerStateId: "STATE_A", defenderStateId: "STATE_B" }, { actionId: "SKIRMISH", year: 40, type: "SKIRMISH", borderRelationId: "BORDER_AB", attackerStateId: "STATE_A", defenderStateId: "STATE_B" }, { actionId: "WAR", year: 40, type: "WAR", borderRelationId: "BORDER_AB", attackerStateId: "STATE_A", defenderStateId: "STATE_B" }, { actionId: "EMBARGO", year: 40, type: "EMBARGO", stateAId: "STATE_A", stateBId: "STATE_B", affectedSettlementIds: ["S1"] }, { actionId: "PIRACY", year: 40, type: "PIRACY", controllerStateId: "STATE_B", affectedRouteIds: ["ROUTE"], affectedSettlementIds: ["S1"] }, { actionId: "BANDITRY", year: 40, type: "BANDITRY", controllerStateId: "STATE_B", affectedRouteIds: ["ROUTE"], affectedSettlementIds: ["S1"] }, { actionId: "SEIZE", year: 40, type: "RESOURCE_SEIZURE", resourceNodeId: "RESOURCE", seizingStateId: "STATE_B", borderRelationId: "BORDER_AB" }, { actionId: "SIEGE", year: 40, type: "SIEGE", attackerStateId: "STATE_B", defenderStateId: "STATE_A", settlementId: "S1", displacementDestinationSettlementId: "S2" }, { actionId: "TREATY", year: 40, type: "TREATY", stateAId: "STATE_A", stateBId: "STATE_B" }]; for (const action of actions) { const result = executeHistoricalConflictActionV5({ state: structuredClone(fixture), canonical, ownerInputs: owner, mode: "DIAGNOSTIC", action }); expect(result.event.entityId).toBe(action.actionId); validatePopulationPartitionV5(result.state); } });
  it("hashes each selected candidate policy document in the causal owner-input boundary", () => { expect(historicalPolicyHashV5(CANDIDATE_HISTORICAL_DYNAMISM_POLICIES_V1.RESOURCE_INDUSTRY)).toMatch(/^[0-9a-f]{64}$/); expect(owner.diagnosticHistoricalPolicyOptIns).toEqual(["RESOURCE_INDUSTRY", "CIVIC_INSTITUTION_SECURITY", "DIPLOMACY_CONFLICT", "DEROGATORY_MEMBERSHIP_SLICING", "PERSECUTION_DISPLACEMENT_ENCLAVE"]); expect(V5_EMPTY_DEROGATORY_DECISION_STREAM_HASH).toMatch(/^[0-9a-f]{64}$/); });
});
